description: Junos OSPF config
type: object
x-examples:
  example-1:
    enabled: true
    areas:
      '0':
        no_summary: false
title: ''
properties:
  enabled:
    type: boolean
    description: whether to rung OSPF on this device
  areas:
    type: object
    description: OSPF areas to run on this device and the corresponding per-area-specific configs
    additionalProperties:
      type: object
      properties:
        no_summary:
          type: boolean
          description: 'for a stub/nssa area, where to avoid forwarding type-3 LSA to this area'
