description: 'optional, if it''s required to have switch''s L3 presense on a network/vlan'
type: object
x-examples:
  example-1:
    type: static
    ip: string
    netmask: string
title: ''
properties:
  type:
    type: string
    enum:
      - static
      - dhcp
    description: static / dhcp (default)
  ip:
    type: string
    description: required if type==static
  netmask:
    type: string
    description: 'optional, `sunbet` from `network` definition will be used if defined  '
