description: ''
type: object
x-examples:
  example-1:
    auth_servers_timeout: 5
    auth_servers_retries: 3
    auth_servers:
      - host: 1.2.3.4
        port: 1812
        secret: testing123
      - host: radius.internal
        port: 1812
        secret: testing123
    acct_servers:
      - host: 1.2.3.4
        port: 1812
        secret: testing123
    acct_interim_interval: 0
properties:
  auth_servers_timeout:
    type: integer
    description: radius auth session timeout, default is 5
  auth_servers_retries:
    description: radius auth session retries, default is 3
    type: integer
  auth_servers:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: ../server_objects/auth_server.v1.yaml
  acct_servers:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: ../server_objects/acct_server.v1.yaml
  acct_interim_interval:
    type: integer
    description: how frequently should interim accounting be reported, 60-65535. default is 0 (use one specified in Access-Accept request from RADIUS Server). Very frequent messages can affect the performance of the radius server, 600 and up is recommended when enabled
