description: ''
type: object
x-examples:
  example-1:
    enabled: true
    groups:
      '0':
        priority: 200
properties:
  enabled:
    type: boolean
  groups:
    type: object
    properties:
      '{vrrp_group}':
        type: object
        properties:
          priority:
            type: number
