description: Junos IP Config
type: object
x-examples:
  example-1:
    type: string
    ip: string
    netmask: string
    gateway: string
    dns:
      - {}
    dns_suffix:
      - {}
    network: string
properties:
  type:
    type: string
    minLength: 1
    default: dynamic
    enum:
      - static
      - dynamic
  ip:
    type: string
    minLength: 1
  netmask:
    type: string
    minLength: 1
    description: used only if `subnet` is not specified in `networks`
  gateway:
    type: string
    minLength: 1
  dns:
    type: array
    items:
      type: string
  dns_suffix:
    type: array
    items:
      type: string
  network:
    type: string
    minLength: 1
    description: 'optional, the network to be used for mgmt'
  dhcp:
    $ref: ./junos_dhcpd.v1.yaml
required:
  - type
