title: junos.gateway_port_config
type: object
x-examples:
  example-1:
    usage: wan
    zone: untrust
    redundancy: true
    ip_config: {}
  example-2:
    usage: wan
    ip_config: {}
properties:
  usage:
    type: string
    description: port usage name
  aggregated:
    type: boolean
    description: default is false
  description:
    type: string
  ip_config:
    $ref: ./junos.ip_config.v1.yaml
  zone:
    type: string
  redundancy:
    type: boolean
required:
  - usage
description: Gateway port config
