description: ''
type: object
x-examples:
  example-1:
    type: string
    ip: string
    netmask: string
    gateway: string
    dns:
      - {}
    dns_suffix:
      - {}
    network: string
properties:
  type:
    type: string
    minLength: 1
  ip:
    type: string
    minLength: 1
  netmask:
    type: string
    minLength: 1
  gateway:
    type: string
    minLength: 1
  dns:
    type: array
    items:
      type: string
  dns_suffix:
    type: array
    items:
      type: string
  network:
    type: string
    minLength: 1
  dhcp:
    $ref: ./junos.dhcp.v1.yaml
required:
  - type
