title: ''
type: object
properties:
  enabled:
    type: boolean
  role:
    type: string
  evpn_id:
    type: integer
    description: unique / generated
  downlinks:
    type: array
    items:
      type: string
  downlink_ips:
    type: array
    items:
      type: string
  pod:
    type: integer
    default: 1
  uplinks:
    type: array
    items:
      type: string
description: EVPN Junos settings
