title: switch_port_config
type: object
x-examples:
  example-1:
    usage: uplink
    aggregated: true
    ae_idx: 0
    ae_disable_lacp: false
    description: to dist-sw-01
  example-dynamic:
    usage: default
    dynamic_usage: dynamic
  example-3:
    usage: ap
properties:
  usage:
    type: string
    description: port usage name
  aggregated:
    type: boolean
    description: default is false
  description:
    type: string
  dynamic_usage:
    type: boolean
    description: 'Enable dynamic usage for this port, default is false'
  ae_idx:
    type: number
    description: Users could force to use the designated AE name
  ae_disable_lacp:
    type: boolean
    description: To disable LACP support for the AE interface
  esilag:
    type: boolean
required:
  - usage
