title: ap_port_config
type: object
properties:
  forwarding:
    type: string
    default: all
    enum:
      - all
      - limited
      - wxtunnel
      - mxtunnel
      - site_mxedge
  vland_ids:
    type: array
    description: if forwrding == limited
    items:
      type: integer
  port_vlan_id:
    type: integer
    description: if forwrding == limited
  wxtunnel_id:
    type: string
    description: if forwarding == wxtunnel
  wxtunnel_remote_id:
    type: string
    description: if forwarding == wxtunnel
  mx_tunnel_id:
    type: string
    description: 'if forwarding == mxtunnel, vlan_ids comes from mxtunnel'
  mxtunnel_name:
    type: string
    description: 'if forwarding == site_mxedge, vlan_ids comes from site_mxedge (`mxtunnels` under site setting)'
  port_auth:
    type: string
    description: whether to do port auth
    default: none
    enum:
      - none
      - dot1x
  enable_mac_auth:
    type: boolean
    description: ''
  disabled:
    type: boolean
  radius_config:
    $ref: ../junos_objects/junos_radius_config.v1.yaml
  radsec:
    $ref: ../server_objects/radsec.v1.yaml
  dynamic_vlan:
    type: object
    description: optional dynamic vlan
    properties:
      enabled:
        type: boolean
      type:
        type: string
      vlans:
        type: object
        additionalProperties:
          type: string
      default_vlan_id:
        type: integer
x-examples:
  example-1:
    forwarding: all
    vland_ids:
      - 0
    port_vlan_id: 0
    wxtunnel_id: string
    wxtunnel_remote_id: string
    mx_tunnel_id: string
    mxtunnel_name: string
    port_auth: none
    enable_mac_auth: true
    disabled: true
    radius_config:
      auth_servers_timeout: 0
      auth_servers_retries: 0
      auth_servers:
        - host: string
          port: 0
          secret: string
      acct_servers:
        - host: string
          secret: string
          port: 0
      acct_interim_interval: 0
    radsec:
      enabled: true
      server_name: string
      servers:
        - host: string
          port: 0
      use_mxedge: true
    dynamic_vlan:
      enabled: true
      type: string
      vlans:
        property1: string
        property2: string
      default_vlan_id: 0
