properties:
  additional_vlan_ids:
    description: additional VLAN IDs, only valid in mesh base mode
    items:
      type: integer
    type: array
  authentication_protocol:
    default: pap
    description: if `enable_mac_auth`==`true`, allows user to select an authentication
      protocol
    enum:
    - pap
    - eap-peap
    - eap-md5
    type: string
  disabled:
    type: boolean
  dynamic_vlan:
    description: optional dynamic vlan
    properties:
      default_vlan_id:
        type: integer
      enabled:
        type: boolean
      type:
        type: string
      vlans:
        additionalProperties:
          type: string
        type: object
    type: object
  enable_mac_auth:
    type: boolean
  forwarding:
    default: all
    enum:
    - all
    - limited
    - wxtunnel
    - mxtunnel
    - site_mxedge
    type: string
  mx_tunnel_id:
    description: if `forwarding`==`mxtunnel`, vlan_ids comes from mxtunnel
    format: uuid
    type: string
  mxtunnel_name:
    description: if `forwarding`==`site_mxedge`, vlan_ids comes from site_mxedge (`mxtunnels`
      under site setting)
    type: string
  port_auth:
    default: none
    description: When doing port auth
    enum:
    - none
    - dot1x
    type: string
  port_vlan_id:
    description: if `forwrding`==`limited`
    type: integer
  radius_config:
    $ref: ./junos_radius_config.yaml
  radsec:
    $ref: ./junos_radius_config.yaml
  vlan_id:
    description: 'optional to specify the vlan id for a tunnel if forwarding is for
      `wxtunnel`, `mxtunnel` or `site_mxedge`.

      * if vlan_id is not specified then it will use first one in vlan_ids[] of the
      mxtunnel.

      * if forwarding == site_mxedge, vlan_ids comes from site_mxedge (`mxtunnels`
      under site setting)'
    type: integer
  vland_ids:
    description: if `forwrding`==`limited`
    items:
      type: integer
    type: array
  wxtunnel_id:
    description: if `forwarding`==`wxtunnel`, the port is bridged to the vlan of the
      session
    type: string
  wxtunnel_remote_id:
    description: if `forwarding`==`wxtunnel`, the port is bridged to the vlan of the
      session
    type: string
title: ap_port_config
type: object
x-examples:
  example-1:
    disabled: true
    dynamic_vlan:
      default_vlan_id: 1
      enabled: true
      type: string
      vlans:
        property1: string
        property2: string
    enable_mac_auth: true
    forwarding: all
    mx_tunnel_id: string
    mxtunnel_name: string
    port_auth: none
    port_vlan_id: 1
    radius_config:
      acct_interim_interval: 0
      acct_servers:
      - host: string
        port: 0
        secret: string
      auth_servers:
      - host: string
        port: 0
        secret: string
      auth_servers_retries: 0
      auth_servers_timeout: 0
    radsec:
      enabled: true
      server_name: string
      servers:
      - host: string
        port: 0
      use_mxedge: true
    vland_ids:
    - 0
    wxtunnel_id: string
    wxtunnel_remote_id: string
