description: ''
properties:
  alert_only:
    type: string
  enabled:
    default: false
    type: boolean
  profile:
    default: strict
    enum:
    - strict
    - standard
    type: string
title: junos_idp_config
type: object
