description: WIP
properties:
  addresses:
    description: if `type`==`custom`, ip subnets
    items:
      type: string
    type: array
  app_caetgories:
    description: list of application categories are available through /api/v1/const/app_categories
    items:
      type: string
    type: array
  apps:
    description: 'when `type`==`app`, comes from `/api/v1/const/apps`

      when `type`==`ssr_app`, comes from `/api/v1/const/ssr_apps`

      when `type`==`srx_app`, comes from `/api/v1/const/srx_apps`

      when `type`==`app_categories`, comes from `/api/v1/const/app_categories`'
    items:
      type: string
    type: array
  created_time:
    readOnly: true
    type: integer
  description:
    type: string
  dscp:
    description: when `traffic_type`==`custom`
    type: integer
  failover_policy:
    default: revertable
    enum:
    - revertable
    - non-revertable
    type: string
  hostnames:
    description: if `type`==`custom`, web filtering
    items:
      example: example.com
      type: string
    type: array
  id:
    format: uuid
    type: string
  max_jitter:
    description: when `traffic_type`==`custom`, for uplink selection
    type: integer
  max_latency:
    description: when `traffic_type`==`custom`, for uplink selection
    type: string
  max_loss:
    description: when `traffic_type`==`custom`, for uplink selection
    type: integer
  modified_time:
    readOnly: true
    type: integer
  name:
    type: string
  org_id:
    format: uuid
    readOnly: true
    type: string
  sle_enabled:
    default: false
    description: whether to enable measure SLE
    type: boolean
  specs:
    description: 'when `type`==`addresses` or `type`==`hostnames`

      if `type`==`custom`, specs is optional. If it doesn''t exist, http and https
      is assumed.'
    items:
      properties:
        port_range:
          example: 8080,8443
          type: string
        protocol:
          default: any
          description: '`https`/ `tcp` / `udp` / `icmp` / `gre` / `any` / `:protocol_number`.

            `protocol_number` is between 1-254'
          example: tcp
          type: string
      type: object
    type: array
    uniqueItems: true
  traffic_class:
    default: best_effort
    description: when `traffic_type`==`custom`
    enum:
    - best_effort
    - high
    - medium
    - low
    type: string
  traffic_type:
    default: data_best_effort
    description: 'values from `/api/v1/consts/traffic_types`

      * when `type`==`apps`, we''ll choose traffic_type automatically

      * when `type`==`addresses` or `type`==`hostnames`, you can provide your own
      settings (optional)'
    type: string
  type:
    default: custom
    enum:
    - app
    - app_categories
    - custom
    - ssr_apps
    - srx_apps
    type: string
  vpn_name:
    enum:
    - addresses
    - apps
    - local
    - hostname
    type: string
title: service
type: object
x-examples:
  example-1:
    addresses:
    - string
    app_caetgories:
    - string
    apps:
    - string
    created_time: 0
    dscp: 0
    failover_policy: revertable
    hostnames:
    - string
    id: 497f6eca-6276-5017-bfeb-53cbbbba6f20
    max_jitter: 0
    max_latency: string
    max_loss: 0
    modified_time: 0
    name: string
    org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
    sle_enabled: false
    specs:
    - port_range: 0
      protocol: any
    traffic_class: best_effort
    traffic_type: data_best_effort
    type: custom
    vpn_name: addresses
