description: 'optional, if it''s required to have switch''s L3 presense on a network/vlan'
type: object
properties:
  type:
    type: string
    enum:
      - static
      - dhcp
    description: |
      static / dhcp (default)
  ip:
    type: string
    description: |
      required if type==static
  netmask:
    type: string
    description: |
      required if type==static
x-examples:
  example-1:
    type: static
    ip: string
    netmask: string
