description: ''
type: object
properties:
  channel_5:
    type: number
  ssids_24:
    type: array
    items:
      required: []
      properties: {}
  radios:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      required:
        - band
        - channel
      properties:
        band:
          type: string
          minLength: 1
        channel:
          type: number
  timestamp:
    type: number
  version:
    type: string
    minLength: 1
  channel_24:
    type: number
  ssids:
    type: array
    items:
      required: []
      properties: {}
  wlans:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      required:
        - id
        - ssid
        - auth
      properties:
        id:
          type: string
          minLength: 1
        bands:
          type: array
          items:
            required: []
            properties: {}
        vlan_ids:
          type: array
          items:
            required: []
            properties: {}
        ssid:
          type: string
          minLength: 1
        auth:
          type: string
          minLength: 1
  radio_macs:
    type: array
    items:
      required: []
      properties: {}
  ssids_5:
    type: array
    items:
      required: []
      properties: {}
  secpolicy_violated:
    type: boolean
required:
  - channel_5
  - ssids_24
  - radios
  - timestamp
  - version
  - channel_24
  - ssids
  - wlans
  - radio_macs
  - ssids_5
  - secpolicy_violated
