content:
  application/json:
    examples:
      example-1:
        value:
          end: 1531862583
          limit: 10
          results:
          - channel_24: 11
            channel_5: 100
            radio_macs:
            - 5c5b352e000a
            - 5c5b352e000b
            - 5c5b352e000c
            radios:
            - band: '24'
              channel: 11
            - band: '5'
              channel: 100
            secpolicy_violated: false
            ssids:
            - test24
            - test5
            ssids_24:
            - test24
            ssids_5:
            - test5
            timestamp: 1531855856.643369
            version: apfw-0.2.14754-cersei-75c8
            wlans:
            - auth: psk
              bands:
              - '24'
              id: be22bba7-8e22-e1cf-5185-b880816fe2cf
              ssid: test24
              vlan_ids:
              - '1'
            - auth: psk
              bands:
              - '5'
              id: f8c18724-4118-3487-811a-f98964988604
              ssid: test5
              vlan_ids:
              - '1'
          start: 1531776183
          total: 1
    schema:
      properties:
        end:
          type: integer
        limit:
          type: integer
        next:
          type: string
        results:
          items:
            properties:
              channel_24:
                type: integer
              channel_5:
                type: integer
              radio_macs:
                items:
                  type: string
                type: array
              radios:
                items:
                  properties:
                    band:
                      type: string
                    channel:
                      type: integer
                  required:
                  - band
                  - channel
                  type: object
                minItems: 1
                type: array
                uniqueItems: true
              secpolicy_violated:
                type: boolean
              ssids:
                items:
                  type: string
                type: array
              ssids_24:
                items:
                  type: string
                type: array
              ssids_5:
                items:
                  type: string
                type: array
              timestamp:
                type: number
              version:
                type: string
              wlans:
                items:
                  properties:
                    auth:
                      type: string
                    bands:
                      items:
                        type: string
                      type: array
                    id:
                      format: uuid
                      type: string
                    ssid:
                      type: string
                    vlan_ids:
                      items:
                        type: string
                      type: array
                  required:
                  - auth
                  - id
                  - ssid
                  type: object
                minItems: 1
                type: array
                uniqueItems: true
            required:
            - channel_24
            - channel_5
            - secpolicy_violated
            - timestamp
            - version
            type: object
          minItems: 1
          type: array
          uniqueItems: true
        start:
          type: integer
        total:
          type: integer
      required:
      - end
      - limit
      - results
      - start
      - total
      type: object
description: OK
