content:
  application/json:
    examples:
      Example:
        value:
        - - app_id: true
            key: 4shared
            name: 4shared
            ssr_app_id: true
    schema:
      items:
        $ref: '../schemas/const_gateway_applications_definition.yml'
      type: array
description: List of Alarm Definitions
title: Constgatewayapplications
