content:
  application/json:
    examples:
      Example:
        value:
        - app_id: true
          app_image_url: ''
          app_probe: true
          category: FileSharing
          group: File Sharing
          key: dropbox
          name: Dropbox
          signature_based: true
          ssr_app_id: true
    schema:
      $ref: '../schemas/const_application_definition_list.yml'
description: List of Applications
title: Constapplications
