content:
  application/json:
    examples:
      Example:
        value:
        - app_id: true
          app_image_url: ''
          app_probe: true
          category: FileSharing
          group: File Sharing
          key: dropbox
          name: Dropbox
          signature_based: true
          ssr_app_id: true
    schema:
      items:
        properties:
          app_id:
            type: boolean
          app_image_url:
            example: '""'
            type: string
          app_probe:
            type: boolean
          category:
            example: FileSharing
            type: string
          group:
            example: File Sharing
            type: string
          key:
            example: dropbox
            type: string
          name:
            example: Dropbox
            type: string
          signature_based:
            type: boolean
          ssr_app_id:
            type: boolean
        type: object
      type: array
description: List of Applications
