content:
  application/json:
    examples:
      Example:
        value:
        - - app_id: true
            key: 4shared
            name: 4shared
            ssr_app_id: true
    schema:
      $ref: '../schemas/const_gateway_applications_definitions.yml'
description: List of Alarm Definitions
title: Constgatewayapplications
