content:
  application/json:
    examples:
      Example:
        value:
          dhcpd_config:
            lan:
              ip_end: 192.168.1.254
              ip_start: 192.168.1.2
          ip_configs:
            lan:
              ip: 192.168.1.1
              type: static
          networks:
            lan:
              name: lan
              subnet: 192.168.1.0/24
              vlan_id: 1
          path_preferences:
            wan:
              paths:
              - name: wan
                type: wan
          port_config:
            cl-1/0/0:
              ip_config:
                type: dhcp
              name: lte
              usage: wan
              wan_type: lte
            ge-0/0/0,ge-0/0/7:
              ip_config:
                type: dhcp
              name: wan
              usage: wan
            ge-0/0/1-6:
              port_network: lan
              usage: lan
          service_policies:
          - action: allow
            name: Internet
            path_preference: wan
            services:
            - any
            tenants:
            - lan
    schema:
      additionalProperties: true
      type: object
description: OK
title: Constdefaultgatewayconfig
