content:
  application/json:
    examples:
      example-1:
        value:
          cli:
          - set system hostname corp-a135
    schema:
      properties:
        cli:
          items:
            type: string
          type: array
      required:
      - cli
      type: object
description: OK
