content:
  application/json:
    examples:
      example-1:
        value:
          cli:
          - set system hostname corp-a135
    schema:
      $ref: '../schemas/response_device_config_cli.yml'
description: OK
title: Deviceconfigcmd
