content:
  application/json:
    examples:
      Failed:
        value:
          bucket: company-private-pcap
          detail: failed to write bucket - 403 AccessDenied
      Success:
        value: {}
    schema:
      $ref: '../schemas/response_pcap_bucket_config.yml'
description: OK
title: Pcapbucketconfig
