content:
  application/json:
    examples:
      Failed:
        value:
          bucket: company-private-pcap
          detail: failed to write bucket - 403 AccessDenied
      Success:
        value: {}
    schema:
      properties:
        bucket:
          type: string
        detail:
          type: string
      type: object
description: OK
title: Pcapbucketconfig
