content:
  application/json:
    examples:
      example-1:
        value:
          addresses:
          - string
          app_caetgories:
          - string
          apps:
          - string
          created_time: 0
          dscp: 0
          failover_policy: revertable
          hostnames:
          - string
          id: 497f6eca-6276-5004-bfeb-53cbbbba6f16
          max_jitter: 0
          max_latency: string
          max_loss: 0
          modified_time: 0
          name: string
          org_id: a40f5d1f-d889-42e9-94ea-b9b33585fc6b
          sle_enabled: false
          specs:
          - port_range: '0'
            protocol: any
          traffic_class: best_effort
          traffic_type: data_best_effort
          type: custom
          vpn_name: addresses
    schema:
      $ref: '../schemas/service.yml'
description: OK
