content:
  application/json:
    examples:
      example-1:
        value:
          apps:
          - app: ZOOM
            degraded: 371103
            duration: 0
            name: ZOOM
            threshold: 173
            total: 1771274
          classifier: ''
          end: 1668760746
          failure: ''
          limit: '1000'
          metric: application-health
          page: 1
          start: 1668121200
          total_count: 1
    schema:
      $ref: '../schemas/sle_impacted_applications.yml'
description: Example response
