content:
  application/json:
    examples:
      Example:
        value:
          created_time: 1508823803
          defaultScopeId: 67970e46-4e12-11e6-9188-0242ad112847
          defaultScopeType: site
          defaultTimeRange:
            end: 1508828400
            endDate: 10/23/2017
            interval: 1d
            name: This Week
            shortName: thisWeek
            start: 1508655600
            usePreset: true
          description: Description of the databoard
          for_site: true
          id: 3bdcc7e8-c04d-4512-b4fc-093da9057eb0
          isCustomDataboard: true
          isScopeLinked: true
          isTimeRangeLinked: true
          modified_time: 0
          name: New Databoard
          org_id: cc079380-5029-4d4a-9125-858de85731ff
          purpose: databoard
          site_id: 67970e46-4e12-11e6-9188-0242ad112847
          tiles:
          - chartBand: 2.4 ghz
            chartColor: '#00B4AD'
            chartDirection: tx + rx
            chartRankBy: string
            chartType: timeSeries
            colspan: 5
            column: 1
            hideEmptyRows: true
            id: 7a9ab38c-cfc3-483d-b51a-0aec571fadc0
            metric:
              apiName: client-dhcp-latency
            name: New Analysis
            row: 1
            rowspan: 2
            scopeId: e0c767834b4c
            scopeType: client
            sortedColumns: null
            timeRange:
              end: 1508823743
              endDate: 10/23/2017
              interval: 1d
              name: Past 7 Days
              shortName: 7d
              start: 1508223600
              usePreset: true
            trendType: line
            vizType: averageTimeSeriesChart
    schema:
      $ref: '../schemas/ui_settings.yml'
description: Example response
