description: CURD UI Settings
properties:
  created_time:
    readOnly: true
    type: number
  defaultScopeId:
    type: string
  defaultScopeType:
    type: string
  defaultTimeRange:
    properties:
      end:
        type: integer
      endDate:
        type: string
      interval:
        type: string
      name:
        type: string
      shortName:
        type: string
      start:
        type: integer
      usePreset:
        type: boolean
    type: object
  description:
    type: string
  for_site:
    readOnly: true
    type: boolean
  id:
    format: uuid
    readOnly: true
    type: string
  isCustomDataboard:
    type: boolean
  isScopeLinked:
    type: boolean
  isTimeRangeLinked:
    type: boolean
  modified_time:
    readOnly: true
    type: number
  name:
    type: string
  org_id:
    format: uuid
    readOnly: true
    type: string
  purpose:
    type: string
  site_id:
    format: uuid
    readOnly: true
    type: string
  tiles:
    items:
      properties:
        chartBand:
          type: string
        chartColor:
          type: string
        chartDirection:
          type: string
        chartRankBy:
          type: string
        chartType:
          type: string
        colspan:
          type: integer
        column:
          type: integer
        hideEmptyRows:
          type: boolean
        id:
          type: string
        metric:
          properties:
            apiName:
              type: string
          type: object
        name:
          type: string
        row:
          type: integer
        rowspan:
          type: integer
        scopeId:
          type: string
        scopeType:
          type: string
        sortedColumns: {}
        timeRange:
          properties:
            end:
              type: number
            endDate:
              type: string
            interval:
              type: string
            name:
              type: string
            shortName:
              type: string
            start:
              type: integer
            usePreset:
              type: boolean
          type: object
        trendType:
          type: string
        vizType:
          type: string
      type: object
    minItems: 1
    type: array
    uniqueItems: true
required:
- description
- id
- for_site
- site_id
- org_id
- created_time
- modified_time
- purpose
title: curd_ui_settings
type: object
x-examples:
  example-1:
    created_time: 1508823803
    defaultScopeId: 67970e46-4e12-11e6-9188-0242ad112847
    defaultScopeType: site
    defaultTimeRange:
      end: 1508828400
      endDate: 10/23/2017
      interval: 1d
      name: This Week
      shortName: thisWeek
      start: 1508655600
      usePreset: true
    description: Description of the databoard
    for_site: true
    id: 3bdcc7e8-c04d-4512-b4fc-093da9057eb0
    isCustomDataboard: true
    isScopeLinked: true
    isTimeRangeLinked: true
    modified_time: 1508823803
    name: New Databoard
    org_id: 6748cfa6-4e12-11e6-9188-0242asfad8365
    purpose: databoard
    site_id: 67970e46-4e12-11e6-9188-0242ad112847
    tiles:
      chartBand: 2.4 ghz
      chartColor: '#00B4AD'
      chartDirection: tx + rx
      chartRankBy: ''
      chartType: timeSeries
      colspan: 5
      column: 1
      hideEmptyRows: true
      id: 7a9ab38c-cfc3-483d-b51a-0aec571fadc0-j956nurl
      metric:
        apiName: client-dhcp-latency
      name: New Analysis
      row: 1
      rowspan: 2
      scopeId: e0c767834b4c
      scopeType: client
      timeRange:
        end: 1508823743
        endDate: 10/23/2017
        interval: 1d
        name: Past 7 Days
        shortName: 7d
        start: 1508223600
        usePreset: true
      trendType: line
      vizType: averageTimeSeriesChart
