description: Junos VRRP config
properties:
  enabled:
    type: boolean
  groups:
    properties:
      '{vrrp_group}':
        properties:
          priority:
            type: integer
        type: object
    type: object
title: junos_vrrp_config
type: object
x-examples:
  example-1:
    enabled: true
    groups:
      '0':
        priority: 200
