properties:
  apps:
    items:
      properties:
        app:
          type: string
        degraded:
          type: integer
        duration:
          type: integer
        name:
          type: string
        threshold:
          type: integer
        total:
          type: integer
      type: object
    type: array
  classifier:
    type: string
  end:
    type: integer
  failure:
    type: string
  limit:
    type: string
  metric:
    type: string
  page:
    type: integer
  start:
    type: integer
  total_count:
    type: integer
title: sle_impacted_applications
type: object
x-examples:
  example-1:
    apps:
    - app: ZOOM
      degraded: 371103
      duration: 0
      name: ZOOM
      threshold: 173
      total: 1771274
    classifier: ''
    end: 1668760746
    failure: ''
    limit: '1000'
    metric: application-health
    page: 1
    start: 1668121200
    total_count: 1
