properties:
  cacert:
    description: Only if `type`==`imagotag` or `type`==`native`
    type: string
  channel:
    description: Only if `type`==`imagotag` or `type`==`native`
    example: 3
    type: integer
  enabled:
    default: false
    description: usb_config is ignored if esl_config enabled
    type: boolean
  host:
    description: Only if `type`==`imagotag` or `type`==`native`
    example: 1.1.1.1
    type: string
  port:
    description: Only if `type`==`imagotag` or `type`==`native`
    example: 0
    type: integer
  type:
    description: 'note: ble_config will be ingored if esl_config is enabled and with
      native mode.'
    enum:
    - imagotag
    - hanshow
    - solum
    - native
    example: imagotag
    type: string
  verify_cert:
    description: Only if `type`==`imagotag` or `type`==`native`
    type: boolean
  vlan_id:
    default: 1
    description: Only if `type`==`solum` or `type`==`hansho`
    type: integer
type: object
