properties:
  auto_provision:
    properties:
      enable:
        type: boolean
      latlng:
        properties:
          lat:
            example: 37.295833
            type: number
          lng:
            example: -122.032946
            type: number
        type: object
      primary:
        properties:
          num_hosts:
            type: string
          wan_names:
            description: optional, only needed if `vars_only`==`false`
            items:
              example: wan0
              type: string
            type: array
        type: object
      region:
        default: auto
        enum:
        - auto
        - EMEA
        - Americas
        - APAC
        type: string
      secondary:
        properties:
          num_hosts:
            type: string
          wan_names:
            description: optional, only needed if `vars_only`==`false`
            items:
              example: wan0
              type: string
            type: array
        type: object
    type: object
  ike_lifetime:
    description: 'Only if:

      * `provider`== `custom-ipsec`'
    type: integer
  ike_mode:
    default: main
    description: 'Only if:

      * `provider`== `custom-ipsec`'
    enum:
    - main
    - aggressive
    type: string
  ike_proposals:
    description: if `provider`== `custom-ipsec`
    items:
      properties:
        auth_algo:
          enum:
          - sha1
          - sha2
          - md5
          type: string
        dh_group:
          default: '14'
          description: "* 1 \n* 2 (1024-bit) \n* 5\n* 14 (default, 2048-bit)\n* 15\
            \ (3072-bit) \n* 16 (4096-bit)\n* 19 (256-bit ECP)\n* 20 (384-bit ECP)\n\
            * 21 (521-bit ECP) \n* 24 (2048-bit ECP)"
          enum:
          - '1'
          - '2'
          - '5'
          - '14'
          - '15'
          - '16'
          - '19'
          - '20'
          - '21'
          - '24'
          type: string
        enc_algo:
          default: aes256
          enum:
          - aes256
          - 3des
          - aes128
          - aes_gcm256
          - aes_gcm128
          nullable: true
          type: string
      type: object
    type: array
  ipsec_lifetime:
    description: if `provider`== `custom-ipsec`
    type: integer
  ipsec_proposals:
    description: 'Only if:

      * `provider`== `custom-ipsec`'
    items:
      properties:
        auth_algo:
          enum:
          - sha1
          - sha2
          - md5
          type: string
        dh_group:
          default: '14'
          description: "Only if:\n* `provider`== `custom-ipsec`\nValues:\n* 1 \n*\
            \ 2 (1024-bit) \n* 5\n* 14 (default, 2048-bit) \n* 15 (3072-bit) \n* 16\
            \ (4096-bit)\n* 19 (256-bit ECP)\n* 20 (384-bit ECP)\n* 21 (521-bit ECP)\
            \ \n* 24 (2048-bit ECP)"
          enum:
          - '1'
          - '2'
          - '5'
          - '14'
          - '15'
          - '16'
          - '19'
          - '20'
          - '21'
          - '24'
          type: string
        enc_algo:
          default: aes256
          enum:
          - aes256
          - 3des
          - aes128
          - aes_gcm128
          - aes_gcm256
          nullable: true
          type: string
      type: object
    type: array
  local_id:
    description: 'Only if:

      * `provider`== `zscaler-ipsec`

      * `provider`==`jse-ipsec`

      * `provider`== `custom-ipsec`'
    type: string
  mode:
    default: active-standby
    enum:
    - active-standby
    - active-active
    type: string
  primary:
    properties:
      hosts:
        items:
          description: IP Address of the remote host
          type: string
        type: array
      internal_ips:
        description: "Only if:\n* `provider`== `zscaler-gre` \n* `provider`== `custom-gre`"
        items:
          type: string
        type: array
      probe_ips:
        items:
          type: string
        type: array
      remote_ids:
        description: 'Only if:

          * `provider`== `custom-ipsec`'
        items:
          type: string
        type: array
      wan_names:
        items:
          type: string
        type: array
    type: object
  probe:
    description: 'Only if:

      * `provider`== `custom-ipsec`'
    properties:
      interval:
        description: how often to trigger the probe
        type: integer
      threshold:
        description: number of consecutive misses before declaring the tunnel down
        type: integer
      timeout:
        description: time within which to complete the connectivity check
        type: integer
      type:
        default: icmp
        enum:
        - icmp
        - http
        type: string
    type: object
  protocol:
    description: 'Only if:

      * `provider`== `custom-ipsec`'
    enum:
    - ipsec
    - gre
    type: string
  provider:
    enum:
    - zscaler-ipsec
    - zscaler-gre
    - customer-gre
    - jse-ipsec
    - custom-ipsec
    type: string
  psk:
    description: 'Only if:

      * `provider`== `zscaler-ipsec`

      * `provider`==`jse-ipsec`

      * `provider`== `custom-ipsec`'
    type: string
  secondary:
    properties:
      hosts:
        items:
          description: IP Address of the remote host
          type: string
        type: array
      internal_ips:
        description: 'Only if:

          * `provider`== `custom-ipsec`'
        items:
          type: string
        type: array
      probe_ips:
        items:
          type: string
        type: array
      remote_ids:
        description: "Only if: \n* `provider`== `custom-ipsec`"
        items:
          type: string
        type: array
      wan_names:
        items:
          type: string
        type: array
    type: object
  version:
    default: '2'
    description: "Only if:\n* `provider`== `custom-gre` \n* `provider`== `custom-ipsec`"
    enum:
    - '1'
    - '2'
    type: string
title: gatewaytemplate_tunnel_configs
type: object
