description: ''
type: object
properties:
  guest:
    type: object
    properties:
      type:
        type: string
        minLength: 1
      ip:
        type: string
        minLength: 1
      netmask:
        type: string
        minLength: 1
    required:
      - type
      - ip
      - netmask
required:
  - guest
x-examples:
  example-1:
    guest:
      type: static
      ip: 10.3.3.1
      netmask: 255.255.255.0
