description: ''
type: object
properties:
  network:
    type: string
    minLength: 1
  type:
    type: string
    minLength: 1
  ip:
    type: string
    minLength: 1
  subnet:
    type: string
    minLength: 1
  gateway:
    type: string
    minLength: 1
  dns:
    type: array
    items:
      type: string
  dns_suffix:
    type: array
    items:
      type: string
  dhcp:
    type: object
    required:
      - enabled
      - type
      - ip_start
      - ip_end
      - servers
    properties:
      enabled:
        type: boolean
      type:
        type: string
        minLength: 1
      ip_start:
        type: string
        minLength: 1
      ip_end:
        type: string
        minLength: 1
      servers:
        type: array
        items:
          type: string
required:
  - network
  - type
  - ip
  - subnet
  - gateway
  - dns
  - dns_suffix
  - dhcp
x-examples:
  example-dhcp_server:
    network: default
    type: static
    ip: 192.168.1.1
    subnet: 192.168.1.0/24
    gateway: 192.168.1.1
    dns:
      - 8.8.8.8
      - 4.4.4.4
    dns_suffix:
      - .mist.local
      - .mist.com
    dhcp:
      enabled: true
      type: local
      ip_start: 192.167.70.100
      ip_end: 192.167.70.200
  example-dhcp_relay:
    network: default
    type: static
    ip: 192.168.1.1
    subnet: 192.168.1.0/24
    gateway: 192.168.1.1
    dns:
      - 8.8.8.8
      - 4.4.4.4
    dns_suffix:
      - .mist.local
      - .mist.com
    dhcp:
      enabled: true
      type: relay
      servers:
        - 11.2.3.4
