properties:
  client_id:
    description: customer account Client ID
    type: string
  client_secret:
    description: customer account Client Secret
    type: string
  instance_url:
    description: customer account VMware instance URL
    type: string
required:
- instance_url
- client_secret
- client_id
title: Account_Vmware_Config
type: object
