properties:
  api_key:
    description: api key to access workspace one uem REST APIs
    type: string
  instance_url:
    description: customer account VMware instance URL
    type: string
  password:
    description: customer account password
    type: string
  username:
    description: customer account user name
    type: string
title: Account_Vmware_Config
type: object
