description: OAuth linked Jamf apps account details
properties:
  client_id:
    description: customer account api client id
    type: string
  client_secret:
    description: customer account api client secret
    type: string
  instance_url:
    description: customer account Jamf instance URL
    example: junipertest.jamfcloud.com
    type: string
  smartgroup_name:
    description: smart group membership for determining compliance status
    example: CompliantGroup1
    type: string
required:
- instance_url
- client_id
- client_secret
- smartgroup_name
title: Account_Jamf_Config
type: object
