description: OAuth linked Zscaler apps account details
properties:
  cloud_name:
    example: zscalerbeta.net
    type: string
  parnter_key:
    example: K35vrZcK3JvrZc
    type: string
  password:
    description: customer account password
    example: password
    type: string
  username:
    description: customer account user name
    example: john@nmo.com
    type: string
required:
- parnter_key
- username
- password
- cloud_name
title: Account_Zscaler_Config
type: object
