properties:
  password:
    description: customer account password
    example: password
    type: string
  username:
    description: customer account user name
    example: john@nmo.com
    type: string
required:
- username
- password
title: Account_Juniper_Config
type: object
