properties:
  cloud_name:
    example: devcentral.juniperclouds.net
    type: string
  password:
    example: foryoureyesonly
    type: string
  username:
    example: john@abc.com
    type: string
required:
- username
- password
title: Account_Jse_Config
type: object
