description: 'additional CLI commands to append to the generated Junos config


  **Note**: no check is done'
items:
  example: set snmp community public
  type: string
title: Additional_Config_Cmds
type: array
