description: IP AP settings
properties:
  dns:
    description: if `type`==`static`
    example:
    - 8.8.8.8
    - 4.4.4.4
    items:
      type: string
    type: array
  dns_suffix:
    description: required if `type`==`static`
    example:
    - .mist.local
    - .mist.com
    items:
      type: string
    type: array
  gateway:
    description: required if `type`==`static`
    example: 10.2.1.254
    format: ipv4
    type: string
  gateway6:
    example: 2607:f8b0:4005:808::1
    format: ipv6
    type: string
  ip:
    description: required if `type`==`static`
    example: 10.2.1.1
    format: ipv4
    type: string
  ip6:
    example: 2607:f8b0:4005:808::2004
    format: ipv6
    type: string
  mtu:
    example: 0
    type: integer
  netmask:
    description: required if `type`==`static`
    example: 255.255.255.0
    type: string
  netmask6:
    example: /32
    type: string
  type:
    $ref: '../schemas/ip_type.yml'
  type6:
    $ref: '../schemas/ip_type6.yml'
  vlan_id:
    default: 1
    description: management vlan id, default is 1 (untagged)
    example: 1
    type: integer
title: Ap_Ip_Config
type: object
