description: optional dynamic vlan
properties:
  default_vlan_id:
    example: 999
    maximum: 4094
    minimum: 1
    type: integer
  enabled:
    type: boolean
  type:
    type: string
  vlans:
    additionalProperties:
      nullable: true
      type: string
    example:
      1-10: null
      user: null
    type: object
title: Ap_Port_Config_Dynamic_Vlan
type: object
