default: pap
description: 'if `enable_mac_auth`==`true`, allows user to select an authentication
  protocol. enum: `eap-md5`, `eap-peap`, `pap`'
enum:
- eap-md5
- eap-peap
- pap
title: Ap_Port_Config_Mac_Auth_Protocol
type: string
