default: all
description: 'enum: `all`, `limited`, `mxtunnel`, `site_mxedge`, `wxtunnel`'
enum:
- all
- limited
- mxtunnel
- site_mxedge
- wxtunnel
example: all
title: Ap_Port_Config_Forwarding
type: string
