description: power related configs
properties:
  base:
    default: 0
    description: additional power to request during negotiating with PSE over PoE,
      in mW
    example: 2000
    type: integer
  prefer_usb_over_wifi:
    default: false
    description: whether to enable power out to peripheral, meanwhile will reduce
      power to wifi (only for AP45 at power mode)
    type: boolean
title: Ap_Pwr_Config
type: object
