properties:
  disabled:
    type: boolean
  dynamic_vlan:
    $ref: '../schemas/ap-port-config-dynamic-vlan.yml'
  enable_mac_auth:
    default: false
    type: boolean
  forwarding:
    $ref: '../schemas/ap-port-config-forwarding.yml'
  mac_auth_protocol:
    $ref: '../schemas/ap-port-config-mac-auth-protocol.yml'
  mist_nac:
    $ref: '../schemas/wlan_mist_nac.yml'
  mx_tunnel_id:
    description: if `forwarding`==`mxtunnel`, vlan_ids comes from mxtunnel
    example: 08cd7499-5841-51c8-e663-fb16b6f3b45e
    format: uuid
    type: string
  mxtunnel_name:
    description: if `forwarding`==`site_mxedge`, vlan_ids comes from site_mxedge (`mxtunnels`
      under site setting)
    type: string
  port_auth:
    $ref: '../schemas/ap-port-config-port-auth.yml'
  port_vlan_id:
    description: if `forwrding`==`limited`
    example: 1
    maximum: 4094
    minimum: 1
    type: integer
  radius_config:
    $ref: '../schemas/junos_radius_config.yml'
  radsec:
    $ref: '../schemas/radsec.yml'
  vlan_id:
    description: 'optional to specify the vlan id for a tunnel if forwarding is for
      `wxtunnel`, `mxtunnel` or `site_mxedge`.

      * if vlan_id is not specified then it will use first one in vlan_ids[] of the
      mxtunnel.

      * if forwarding == site_mxedge, vlan_ids comes from site_mxedge (`mxtunnels`
      under site setting)'
    example: 9
    maximum: 4094
    minimum: 1
    type: integer
  vland_ids:
    $ref: '../schemas/ap-port-config-vland-ids.yml'
  wxtunnel_id:
    description: if `forwarding`==`wxtunnel`, the port is bridged to the vlan of the
      session
    example: 7dae216d-7c98-a51b-e068-dd7d477b7216
    format: uuid
    type: string
  wxtunnel_remote_id:
    description: if `forwarding`==`wxtunnel`, the port is bridged to the vlan of the
      session
    example: wifiguest
    type: string
title: ap_port_config
type: object
