properties:
  additional_vlan_ids:
    description: additional VLAN IDs, only valid in mesh base mode
    example:
    - 55
    - 66
    items:
      maximum: 409
      minimum: 1
      type: integer
    type: array
  disabled:
    type: boolean
  dynamic_vlan:
    description: optional dynamic vlan
    properties:
      default_vlan_id:
        example: 999
        maximum: 4094
        minimum: 1
        type: integer
      enabled:
        type: boolean
      type:
        type: string
      vlans:
        additionalProperties:
          nullable: true
          type: string
        example:
          1-10: null
          user: null
        type: object
    type: object
  enable_mac_auth:
    default: false
    type: boolean
  forwarding:
    default: all
    enum:
    - all
    - limited
    - wxtunnel
    - mxtunnel
    - site_mxedge
    example: all
    type: string
  mac_auth_protocol:
    default: pap
    description: if `enable_mac_auth`==`true`, allows user to select an authentication
      protocol
    enum:
    - pap
    - eap-peap
    - eap-md5
    type: string
  mist_nac:
    properties:
      enabled:
        default: false
        type: boolean
    type: object
  mx_tunnel_id:
    description: if `forwarding`==`mxtunnel`, vlan_ids comes from mxtunnel
    example: 08cd7499-5841-51c8-e663-fb16b6f3b45e
    format: uuid
    type: string
  mxtunnel_name:
    description: if `forwarding`==`site_mxedge`, vlan_ids comes from site_mxedge (`mxtunnels`
      under site setting)
    type: string
  port_auth:
    default: none
    description: When doing port auth
    enum:
    - none
    - dot1x
    example: none
    type: string
  port_vlan_id:
    description: if `forwrding`==`limited`
    example: 1
    maximum: 4094
    minimum: 1
    type: integer
  radius_config:
    $ref: '../schemas/junos_radius_config.yml'
  radsec:
    $ref: '../schemas/radsec.yml'
  vlan_id:
    description: 'optional to specify the vlan id for a tunnel if forwarding is for
      `wxtunnel`, `mxtunnel` or `site_mxedge`.

      * if vlan_id is not specified then it will use first one in vlan_ids[] of the
      mxtunnel.

      * if forwarding == site_mxedge, vlan_ids comes from site_mxedge (`mxtunnels`
      under site setting)'
    example: 9
    maximum: 4094
    minimum: 1
    type: integer
  vland_ids:
    description: if `forwrding`==`limited`
    example:
    - 1
    - 10
    - 50
    items:
      maximum: 4094
      minimum: 1
      type: integer
    type: array
  wxtunnel_id:
    description: if `forwarding`==`wxtunnel`, the port is bridged to the vlan of the
      session
    example: 7dae216d-7c98-a51b-e068-dd7d477b7216
    format: uuid
    type: string
  wxtunnel_remote_id:
    description: if `forwarding`==`wxtunnel`, the port is bridged to the vlan of the
      session
    example: wifiguest
    type: string
title: ap_port_config
type: object
