properties:
  bandwidth:
    example: 20
    type: number
  channel:
    example: 1
    type: integer
  dynamic_chaining_enabled:
    example: false
    type: boolean
  power:
    example: 10
    type: number
  rx_chain:
    example: 4
    type: integer
  tx_chain:
    example: 4
    type: integer
title: Ap_Stats_Radio_Config_Band
type: object
