properties:
  band_24:
    $ref: '../schemas/ap_stats_radio_config_band.yml'
  band_5:
    $ref: '../schemas/ap_stats_radio_config_band.yml'
  band_6:
    $ref: '../schemas/ap_stats_radio_config_band.yml'
  scanning_enabled:
    type: boolean
title: Ap_Stats_Radio_Config
type: object
