properties:
  beacon_rate:
    type: integer
  beacon_rate_model:
    example: custom
    type: string
  beam_disabled:
    items:
      type: integer
    type: array
  power:
    type: integer
  power_mode:
    example: custom
    type: string
title: Ap_Stats_Ble_Config
type: object
