properties:
  beacon_rate:
    type: integer
  beacon_rate_model:
    example: custom
    type: string
  beam_disabled:
    $ref: '../schemas/ap-stats-ble-config-beam-disabled.yml'
  power:
    type: integer
  power_mode:
    example: custom
    type: string
title: Ap_Stats_Ble_Config
type: object
