properties:
  allow_rrm_disable:
    nullable: true
    readOnly: true
    type: boolean
  bandwidth:
    example: 20
    nullable: true
    readOnly: true
    type: number
  channel:
    example: 1
    type: integer
  disabled:
    nullable: true
    readOnly: true
    type: boolean
  dynamic_chaining_enabled:
    example: false
    nullable: true
    readOnly: true
    type: boolean
  power:
    example: 10
    nullable: true
    readOnly: true
    type: number
  power_max:
    example: 10
    nullable: true
    readOnly: true
    type: number
  power_min:
    example: 10
    nullable: true
    readOnly: true
    type: number
  rx_chain:
    example: 4
    nullable: true
    readOnly: true
    type: integer
  tx_chain:
    example: 4
    nullable: true
    readOnly: true
    type: integer
title: Ap_Stats_Radio_Config_Band
type: object
