properties:
  dot1x:
    default: false
    description: Whether to do 802.1x against uplink switch. When enaled, AP cert
      will be used to do EAP-TLS and the Org's CA Cert has to be provisioned at the
      switch
    type: boolean
  keep_wlans_up_if_down:
    default: false
    description: by default, WLANs are disabled when uplink is down. In some scenario,
      like SiteSurvey, one would want the AP to keep sending beacons.
    type: boolean
title: Ap_Uplink_Port_Config
type: object
