properties:
  disabled:
    default: false
    description: If true, the BGP session to this neighbor will be administratively
      disabled/shutdown
    type: boolean
  export_policy:
    type: string
  hold_time:
    default: 90
    maximum: 65535
    minimum: 0
    type: integer
  import_policy:
    type: string
  multihop_ttl:
    description: assuming BGP neighbor is directly connected
    maximum: 255
    minimum: 0
    type: integer
  neighbor_as:
    type: integer
title: Bgp_Config_Neighbors
type: object
