description: list of AP BLE location beam numbers (1-8) which should be disabled at
  the AP and not transmit location information (where beam 1 is oriented at the top
  the AP, growing counter-clock-wise, with 9 being the omni BLE beam)
example:
- 1
- 3
- 6
items:
  type: integer
title: Ble_Config_Beam_Disabled
type: array
