properties:
  configuration:
    type: string
  control_link_info:
    $ref: '../schemas/cluster_config_stats_control_link_info.yml'
  ethernet_connection:
    $ref: '../schemas/cluster_config_stats_ethernet_connection.yml'
  fabric_link_info:
    $ref: '../schemas/cluster_config_stats_fabric_link_info.yml'
  last_status_change_reason:
    type: string
  operational:
    type: string
  primary_node_health:
    type: string
  redundancy_group_information:
    $ref: '../schemas/cluster_config_stats_redundancy_group_info.yml'
  secondary_node_health:
    type: string
  status:
    type: string
title: Cluster_Config_Stats
type: object
