properties:
  DataPlaneNotifiedStatus:
    type: string
  Interface:
    $ref: '../schemas/strings.yml'
  InternalStatus:
    type: string
  State:
    type: string
  Status:
    type: string
title: Cluster_Config_Stats_Fabric_Link_Info
type: object
