additionalProperties:
  $ref: '../schemas/config_switch_local_accounts_user.yml'
description: Property key is the user name. For Local user authentication
title: Config_Switch_Local_Accounts
type: object
