description: Switch settings
properties:
  ap_affinity_threshold:
    default: 10
    description: ap_affinity_threshold ap_affinity_threshold can be added as a field
      under site/setting. By default this value is set to 12. If the field is set
      in both site/setting and org/setting, the value from site/setting will be used.
    type: integer
  cli_banner:
    description: Set Banners for switches. Allows markup formatting
    example: \t\tWELCOME!
    type: string
  cli_idle_timeout:
    description: Sets timeout for switches
    maximum: 60
    minimum: 1
    type: integer
  config_revert_timer:
    default: 10
    description: the rollback timer for commit confirmed
    maximum: 30
    minimum: 1
    type: integer
  dhcp_option_fqdn:
    default: false
    description: Enable to provide the FQDN with DHCP option 81
    type: boolean
  local_accounts:
    $ref: '../schemas/config_switch_local_accounts.yml'
  mxedge_proxy_host:
    type: string
  mxedge_proxy_port:
    default: 2222
    type: integer
  protect_re:
    $ref: '../schemas/protect_re.yml'
  radius:
    $ref: '../schemas/config-switch-radius.yml'
  root_password:
    type: string
  tacacs:
    $ref: '../schemas/tacacs.yml'
  use_mxedge_proxy:
    description: to use mxedge as proxy
    type: boolean
title: Config_Switch
type: object
