description: by default, `radius_config` will be used. if a different one has to be
  used set `use_different_radius
properties:
  enabled:
    type: boolean
  radius_config:
    $ref: '../schemas/junos_radius_config.yml'
  use_different_radius:
    type: string
title: Config-Switch-Radius
type: object
