description: Switch site settings
properties:
  ap_affinity_threshold:
    default: 10
    description: ap_affinity_threshold ap_affinity_threshold can be added as a field
      under site/setting. By default this value is set to 12. If the field is set
      in both site/setting and org/setting, the value from site/setting will be used.
    type: integer
  config_revert_timer:
    default: 10
    description: the rollback timer for commit confirmed
    maximum: 30
    minimum: 1
    type: number
  dhcp_option_fqdn:
    default: false
    description: Enable to provide the FQDN with DHCP option 81
    type: boolean
  mxedge_proxy_host:
    type: string
  mxedge_proxy_port:
    default: 2222
    type: integer
  protect_re:
    $ref: '../schemas/protect_re.yml'
  radius:
    description: by default, `radius_config` will be used. if a different one has
      to be used set `use_different_radius
    properties:
      enabled:
        type: boolean
      radius_config:
        $ref: '../schemas/junos_radius_config.yml'
      use_different_radius:
        type: string
    type: object
  root_password:
    type: string
  tacacs:
    $ref: '../schemas/tacacs.yml'
  use_mxedge_proxy:
    description: to use mxedge as proxy
    type: boolean
title: Config_Switch
type: object
