properties:
  members:
    items:
      properties:
        member:
          type: number
        vc_ports:
          items:
            type: string
          type: array
      required:
      - member
      title: config_vc_port_member
      type: object
    minItems: 1
    type: array
    uniqueItems: true
  op:
    enum:
    - set
    - delete
    minLength: 1
    title: VC Port Operation
    type: string
required:
- op
- members
title: Config_Vc_Port
type: object
