properties:
  app_id:
    type: boolean
  app_image_url:
    example: '""'
    type: string
  app_probe:
    type: boolean
  category:
    example: FileSharing
    type: string
  group:
    example: File Sharing
    type: string
  key:
    example: dropbox
    type: string
  name:
    example: Dropbox
    type: string
  signature_based:
    type: boolean
  ssr_app_id:
    type: boolean
title: Const_Application_Definition
type: object
