properties:
  app_id:
    example: true
    type: boolean
  key:
    example: 4shared
    type: string
  name:
    example: 4shared
    type: string
  ssr_app_id:
    example: true
    type: boolean
title: Const_Gateway_Applications_Definition
type: object
