description: 'enum: `boolean`, `hex`, `int16`, `int32`, `ip`, `string`, `uint16`,
  `uint32`'
enum:
- boolean
- hex
- int16
- int32
- ip
- string
- uint16
- uint32
title: Dhcpd_Config_Option_Type
type: string
