additionalProperties:
  $ref: '../schemas/dhcpd_config_fixed_binding.yml'
description: Property key is the MAC Address
example:
  5684dae9ac8b:
    ip: 192.168.70.35
    name: John
title: Dhcpd_Config_Fixed_Bindings
type: object
