additionalProperties:
  $ref: '../schemas/dhcpd_config.yml'
properties:
  enabled:
    default: false
    description: if set to `true`, disable the DHCP server
    type: boolean
title: Dhcpd_Configs
type: object
