additionalProperties:
  $ref: '../schemas/dhcpd_config.yml'
description: if DHCP Server/Relay is intended. Property key is the network name
properties:
  enabled:
    type: boolean
title: Dhcpd_Configs
type: object
