properties:
  dns_servers:
    $ref: '../schemas/dhcpd_config_dns_servers.yml'
  dns_suffix:
    $ref: '../schemas/dhcpd_config_dns_suffix.yml'
  enabled:
    default: false
    description: when defined in template, this allows device to override
    type: boolean
  fixed_bindings:
    $ref: '../schemas/dhcpd_config_fixed_bindings.yml'
  gateway:
    description: if `type`==`local` - optional, `ip` will be used if not provided
    example: 192.168.70.1
    type: string
  ip_end:
    description: if `type`==`local`
    example: 192.168.70.200
    type: string
  ip_end6:
    description: if `type6`==`local`
    example: 2607:f8b0:4005:808::ff
    type: string
  ip_start:
    description: if `type`==`local`
    example: 192.168.70.100
    type: string
  ip_start6:
    description: if `type6`==`local`
    example: 2607:f8b0:4005:808::2
    type: string
  lease_time:
    default: 86400
    description: in seconds, lease time has to be between 3600 [1hr] - 604800 [1 week],
      default is 86400 [1 day]
    maximum: 604800
    minimum: 3600
    type: integer
  options:
    $ref: '../schemas/dhcpd_config_options.yml'
  server_id_override:
    default: false
    description: "`server_id_override`==`true` means the device, when acts as DHCP\
      \ relay and forwards DHCP responses from DHCP server to clients, \nshould overwrite\
      \ the Sever Identifier option (i.e. DHCP option 54) in DHCP responses with its\
      \ own IP address."
    type: boolean
  servers:
    $ref: '../schemas/dhcpd_config_servers.yml'
  servers6:
    $ref: '../schemas/dhcpd_config_servers6.yml'
  type:
    $ref: '../schemas/dhcpd_config_type.yml'
  type6:
    $ref: '../schemas/dhcpd_config_type6.yml'
  vendor_encapulated:
    $ref: '../schemas/dhcpd_config_vendor_options.yml'
title: Dhcpd_Config
type: object
