additionalProperties:
  $ref: '../schemas/dhcpd_config_property.yml'
properties:
  enabled:
    default: false
    description: if set to `true`, enable the DHCP server
    type: boolean
title: Dhcpd_Config
type: object
