properties:
  auto_provision:
    properties:
      enable:
        type: boolean
      latlng:
        $ref: '../schemas/lat_lng.yml'
      primary:
        $ref: '../schemas/gateway_template_tunnel_auto_provision_node.yml'
      region:
        $ref: '../schemas/gateway_template_tunnel_auto_provision_region.yml'
      secondary:
        $ref: '../schemas/gateway_template_tunnel_auto_provision_node.yml'
    type: object
  ike_lifetime:
    description: 'Only if:

      * `provider`== `custom-ipsec`'
    type: integer
  ike_mode:
    $ref: '../schemas/gateway_template_tunnel_ike_mode.yml'
  ike_proposals:
    description: if `provider`== `custom-ipsec`
    items:
      properties:
        auth_algo:
          $ref: '../schemas/gateway_template_tunnel_configs_auth_algo.yml'
        dh_group:
          $ref: '../schemas/gateway_template_tunnel_ike_dh_group.yml'
        enc_algo:
          $ref: '../schemas/gateway_template_tunnel_configs_enc_algo.yml'
      title: gateway_template_tunnel_ike_proposal
      type: object
    type: array
  ipsec_lifetime:
    description: if `provider`== `custom-ipsec`
    type: integer
  ipsec_proposals:
    description: 'Only if:

      * `provider`== `custom-ipsec`'
    items:
      $ref: '../schemas/gateway_template_tunnel_ipsec_proposal.yml'
    type: array
  local_id:
    description: 'Only if:

      * `provider`== `zscaler-ipsec`

      * `provider`==`jse-ipsec`

      * `provider`== `custom-ipsec`'
    type: string
  mode:
    $ref: '../schemas/gateway_template_tunnel_mode.yml'
  primary:
    $ref: '../schemas/gateway_template_tunnel_node.yml'
  probe:
    $ref: '../schemas/gateway_template_tunnel_probe.yml'
  protocol:
    $ref: '../schemas/gateway_template_tunnel_protocol.yml'
  provider:
    $ref: '../schemas/gateway_template_tunnel_provider_name.yml'
  psk:
    description: 'Only if:

      * `provider`== `zscaler-ipsec`

      * `provider`==`jse-ipsec`

      * `provider`== `custom-ipsec`'
    type: string
  secondary:
    $ref: '../schemas/gateway_template_tunnel_node.yml'
  version:
    $ref: '../schemas/gateway_template_tunnel_version.yml'
title: Gateway_Template_Tunnel_Configs
type: object
