properties:
  class_percentages:
    $ref: '../schemas/gateway-port-config-traffic-shaping-class-percentages.yml'
  enabled:
    default: false
    type: boolean
title: Gateway-Port-Config-Traffic-Shaping
type: object
