description: Junos IP Config
properties:
  dns:
    $ref: '../schemas/gateway_ip_config_dns_servers.yml'
  dns_suffix:
    $ref: '../schemas/gateway_ip_config_dns_suffix.yml'
  gateway:
    description: except for out-of_band interface (vme/em0/fxp0)
    type: string
  ip:
    type: string
  netmask:
    description: used only if `subnet` is not specified in `networks`
    type: string
  network:
    description: optional, the network to be used for mgmt
    type: string
  poser_password:
    description: if `type`==`pppoe`
    type: string
  pppoe_auth:
    $ref: '../schemas/gateway_wan_ppoe_auth.yml'
  pppoe_username:
    description: if `type`==`pppoe`
    type: string
  type:
    $ref: '../schemas/gateway_wan_type.yml'
title: Gateway_Ip_Config
type: object
