properties:
  bfd_profile:
    $ref: '../schemas/gateway-port-config-vpn-paths-additional-properties-bfd-profile.yml'
  bfd_use_tunnel_mode:
    default: false
    description: whether to use tunnel mode. SSR only
    type: boolean
  role:
    $ref: '../schemas/gateway-port-config-vpn-paths-additional-properties-role.yml'
  traffic_shaping:
    $ref: '../schemas/gateway-port-config-vpn-paths-additional-properties-traffic-shaping.yml'
title: Gateway-Port-Config-Vpn-Paths-Additional-Properties
type: object
