additionalProperties:
  $ref: '../schemas/gateway-port-config-vpn-paths-additional-properties.yml'
properties:
  preference:
    description: for a given VPN, when path_selection.strategy=simple, the preference
      for a path (lower is preferred)
    type: integer
title: Gateway-Port-Config-Vpn-Paths
type: object
