description: 'percentages for differet class of traffic: high / medium / low / best-effort

  sum must be equal to 100'
items:
  type: integer
title: Gateway-Port-Config-Vpn-Paths-Additional-Properties-Traffic-Shaping-Class-Percentage
type: array
