properties:
  ip:
    format: ipv4
    type: string
  netmask:
    example: /24
    type: string
  secondary_ips:
    $ref: '../schemas/gateway_template_ip_config_second_ips.yml'
title: Gateway_Template_Ip_Config
type: object
