description: optional, by default, source-NAT is performed on all WAN Ports using
  the interface-ip
properties:
  disabled:
    default: false
    description: or to disable the source-nat
    type: boolean
  nat_pool:
    description: if alternative nat_pool is desired
    example: 64.2.4.0/30
    type: string
title: Gateway-Port-Config-Wan-Source-Nat
type: object
