description: Gateway port config
properties:
  description:
    type: string
  disable_autoneg:
    default: false
    type: boolean
  disabled:
    default: false
    description: port admin up (true) / down (false)
    type: boolean
  dsl_type:
    $ref: '../schemas/gateway_port_dsl_type.yml'
  dsl_vci:
    default: 35
    description: 'if `wan_type`==`dsl`

      16 bit int'
    type: integer
  dsl_vpi:
    default: 0
    description: 'if `wan_type`==`dsl`

      8 bit int'
    type: integer
  duplex:
    $ref: '../schemas/gateway_port_duplex.yml'
  ip_config:
    $ref: '../schemas/gateway_ip_config.yml'
  lte_apn:
    description: if `wan_type`==`lte`
    type: string
  lte_auth:
    $ref: '../schemas/gateway_port_lte_auth.yml'
  lte_backup:
    type: boolean
  lte_password:
    description: if `wan_type`==`lte`
    type: string
  lte_username:
    description: if `wan_type`==`lte`
    type: string
  mtu:
    type: integer
  name:
    description: name that we'll use to derive config
    type: string
  networks:
    $ref: '../schemas/gateway_port_networks.yml'
  outer_vlan_id:
    description: for Q-in-Q
    type: integer
  poe_disabled:
    default: false
    type: boolean
  port_network:
    description: if `usage`==`lan`
    type: string
  preserve_dscp:
    default: true
    description: whether to preserve dscp when sending traffic over VPN (SSR-only)
    type: boolean
  redundant:
    description: if HA mode
    type: boolean
  reth_idx:
    description: if HA mode
    type: integer
  reth_node:
    description: if HA mode
    type: string
  reth_nodes:
    $ref: '../schemas/gateway_port_reth_nodes.yml'
  speed:
    default: auto
    example: 1g
    type: string
  ssr_no_virtual_mac:
    default: false
    description: when SSR is running as VM, this is required on certain hosting platforms
    type: boolean
  svr_port_range:
    default: none
    description: for SSR only
    example: 60000-60005
    type: string
  traffic_shaping:
    $ref: '../schemas/gateway_port_traffic_shaping.yml'
  usage:
    $ref: '../schemas/gateway_port_usage.yml'
  vlan_id:
    description: if WAN interface is on a VLAN
    type: integer
  vpn_paths:
    $ref: '../schemas/gateway_port_vpn_paths.yml'
  wan_arp_policer:
    $ref: '../schemas/gateway_port_wan_arp_policer.yml'
  wan_ext_ip:
    description: optional, if spoke should reach this port by a different IP
    type: string
  wan_source_nat:
    $ref: '../schemas/gateway_port_wan_source_nat.yml'
  wan_type:
    $ref: '../schemas/gateway_port_wan_type.yml'
required:
- usage
title: Gateway_Port_Config
type: object
