description: Gateway port config
properties:
  description:
    type: string
  disable_autoneg:
    default: false
    type: boolean
  dsl_type:
    default: vdsl
    description: if `wan_type`==`lte`
    enum:
    - vdsl
    - adsl
    type: string
  dsl_vci:
    default: 35
    description: 'if `wan_type`==`dsl`

      16 bit int'
    type: integer
  dsl_vpi:
    default: 0
    description: 'if `wan_type`==`dsl`

      8 bit int'
    type: integer
  duplex:
    default: auto
    enum:
    - half
    - full
    - auto
    example: full
    type: string
  ip_config:
    $ref: '../schemas/junos_ip_config_gateway.yml'
  lte_apn:
    description: if `wan_type`==`lte`
    type: string
  lte_auth:
    default: none
    description: if `wan_type`==`lte`
    enum:
    - none
    - chap
    - pap
    type: string
  lte_backup:
    type: boolean
  lte_password:
    description: if `wan_type`==`lte`
    type: string
  lte_username:
    description: if `wan_type`==`lte`
    type: string
  mtu:
    type: integer
  name:
    description: name that we'll use to derive config
    type: string
  networks:
    description: if `usage`==`lan`
    items:
      type: string
    type: array
  outer_vlan_id:
    description: for Q-in-Q
    type: integer
  poe_disabled:
    default: false
    type: boolean
  port_network:
    description: if `usage`==`lan`
    type: string
  preserve_dscp:
    default: true
    description: whether to preserve dscp when sending traffic over VPN (SSR-only)
    type: boolean
  redundant:
    description: if HA mode
    type: boolean
  reth_idx:
    description: if HA mode
    type: integer
  reth_node:
    description: if HA mode
    type: string
  speed:
    default: auto
    example: 1g
    type: string
  svr_port_range:
    default: none
    description: for SSR only
    example: 60000-60005
    type: string
  traffic_shaping:
    properties:
      class_percentages:
        description: 'percentages for differet class of traffic: high / medium / low
          / best-effort

          sum must be equal to 100'
        items:
          type: integer
        type: array
      enabled:
        default: false
        type: boolean
    type: object
  usage:
    description: port usage name
    enum:
    - lan
    - wan
    - ha_data
    - ha_control
    type: string
  vlan_id:
    description: if WAN interface is on a VLAN
    type: integer
  vpn_paths:
    additionalProperties:
      properties:
        bfd_profile:
          default: broadband
          enum:
          - lte
          - broadband
          type: string
        bfd_use_tunnel_mode:
          default: false
          description: whether to use tunnel mode. SSR only
          type: boolean
        role:
          default: spoke
          enum:
          - spoke
          - hub
          type: string
        traffic_shaping:
          properties:
            class_percentage:
              description: 'percentages for differet class of traffic: high / medium
                / low / best-effort

                sum must be equal to 100'
              items:
                type: integer
              type: array
            enabled:
              type: boolean
            max_tx_kbps:
              type: integer
          type: object
      type: object
    properties:
      preference:
        description: 'for a given VPN, when path_selection.strategy=simple, the preference
          for a path (lower is preferred) '
        type: integer
    type: object
  wan_ext_ip:
    description: optional, if spoke should reach this port by a different IP
    type: string
  wan_source_nat:
    description: optional, by default, source-NAT is performed on all WAN Ports using
      the interface-ip
    properties:
      disabled:
        default: false
        description: or to disable the source-nat
        type: boolean
      nat_pool:
        description: if alternative nat_pool is desired
        example: 64.2.4.0/30
        type: string
    type: object
  wan_type:
    default: broadband
    description: if `usage`==`wan`
    enum:
    - broadband
    - dsl
    - lte
    type: string
required:
- usage
type: object
