properties:
  ip:
    format: ipv4
    type: string
  netmask:
    example: /24
    type: string
  secondary_ips:
    $ref: '../schemas/gateway_ip_config_property_second_ips.yml'
  type:
    $ref: '../schemas/ip_type.yml'
title: Gateway_Ip_Config_Property
type: object
