properties:
  class_percentage:
    $ref: '../schemas/gateway-port-config-vpn-paths-additional-properties-traffic-shaping-class-percentage.yml'
  enabled:
    type: boolean
  max_tx_kbps:
    type: integer
title: Gateway-Port-Config-Vpn-Paths-Additional-Properties-Traffic-Shaping
type: object
