additionalProperties:
  properties:
    ip:
      format: ipv4
      type: string
    netmask:
      example: /24
      type: string
    secondary_ips:
      description: optional list of secondary IPs in CIDR format
      example:
      - 192.168.50.1/24
      - 192.168.60.1/26
      items:
        type: string
      type: array
  type: object
description: Property key is the network name
title: Gateway_Ip_Config
type: object
