description: out-of-band (vme/em0/fxp0) IP config
properties:
  gateway:
    description: if `type`==`static`
    type: string
  ip:
    description: if `type`==`static`
    type: string
  netmask:
    description: if `type`==`static`
    type: string
  node1:
    $ref: '../schemas/gateway_oob_ip_config_node1.yml'
  type:
    $ref: '../schemas/ip_type.yml'
  use_mgmt_vrf:
    default: false
    description: if supported on the platform. If enabled, DNS will be using this
      routing-instance, too
    type: boolean
  use_mgmt_vrf_for_host_out:
    default: false
    description: for host-out traffic (NTP/TACPLUS/RADIUS/SYSLOG/SNMP), if alternative
      source network/ip is desired,
    type: boolean
  vlan_id:
    type: string
title: Gateway_Oob_Ip_Config
type: object
