properties:
  ip:
    format: ipv4
    type: string
  netmask:
    example: /24
    type: string
  secondary_ips:
    $ref: '../schemas/gateway-ip-config-additional-properties-second-ips.yml'
title: Gateway-Ip-Config-Additional-Properties
type: object
