properties:
  enable:
    type: boolean
  latlng:
    $ref: '../schemas/lat_lng.yml'
  primary:
    $ref: '../schemas/gateway_template_tunnel_auto_provision_node.yml'
  region:
    $ref: '../schemas/gateway_template_tunnel_auto_provision_region.yml'
  secondary:
    $ref: '../schemas/gateway_template_tunnel_auto_provision_node.yml'
title: Gateway-Template-Tunnel-Configs-Auto-Provision
type: object
