properties:
  disable_auto_config:
    description: if the device is claimed
    type: boolean
  managed:
    description: if the device is adopted
    type: boolean
  nodes:
    $ref: '../schemas/ha_cluster_config_nodes.yml'
  site_id:
    example: 43e9c864-a7e4-4310-8031-d9817d2c5a43
    format: uuid
    type: string
title: Ha_Cluster_Config
type: object
