properties:
  disable_auto_config:
    description: if the device is claimed
    type: boolean
  managed:
    description: if the device is adopted
    type: boolean
  nodes:
    items:
      maxProperties: 2
      properties:
        mac:
          description: node mac, should be unassigned
          example: aff827549235
          type: string
      title: cluster_node
      type: object
    type: array
  site_id:
    $ref: '../schemas/site_id.yml'
title: Ha_Cluster_Config
type: object
