properties:
  alert_only:
    type: string
  enabled:
    default: false
    type: boolean
  idpprofile_id:
    description: org-level IDP Profile can be used, this takes precedence over `profile`
    example: 89b9d208-84a4-fa8f-af57-78f92c639cf2
    format: uuid
    type: string
  profile:
    default: strict
    description: '`strict` (default) / `standard` / or keys from from idp_profiles'
    type: string
title: Idp_Config
type: object
