description: Switch port config
properties:
  ae_disable_lacp:
    description: To disable LACP support for the AE interface
    type: boolean
  ae_idx:
    description: Users could force to use the designated AE name
    type: integer
  ae_lacp_slow:
    default: true
    description: to use fast timeout
    type: boolean
  aggregated:
    default: false
    type: boolean
  critical:
    description: if want to generate port up/down alarm
    type: boolean
  description:
    type: string
  disable_autoneg:
    default: false
    description: if `speed` and `duplex` are specified, whether to disable autonegotiation
    type: boolean
  duplex:
    $ref: '../schemas/junos_port_config_duplex.yml'
  dynamic_usage:
    description: Enable dynamic usage for this port. Set to `dynamic` to enable.
    nullable: true
    type: string
  esilag:
    type: boolean
  mtu:
    default: 1514
    description: media maximum transmission unit (MTU) is the largest data unit that
      can be forwarded without fragmentation
    type: integer
  no_local_overwrite:
    description: prevent helpdesk to override the port config
    type: boolean
  poe_disabled:
    default: false
    type: boolean
  speed:
    $ref: '../schemas/junos_port_config_speed.yml'
  usage:
    description: "port usage name. \n\nIf EVPN is used, use `evpn_uplink`or `evpn_downlink`"
    type: string
required:
- usage
title: Junos_Port_Config
type: object
