description: if `type`==`local` - optional, if not defined, system one will be used
example:
- .mist.local
- .mist.com
items:
  type: string
title: Junos-Dhcpd-Config-Additional-Properties-Dns-Suffix
type: array
