description: Junos IP Config
properties:
  dns:
    $ref: '../schemas/strings.yml'
  dns_suffix:
    $ref: '../schemas/strings.yml'
  gateway:
    type: string
  ip:
    type: string
  netmask:
    description: used only if `subnet` is not specified in `networks`
    type: string
  network:
    description: the network where this mgmt IP reside, this will be used as default
      network for outbound-ssh, dns, ntp, dns, tacplus, radius, syslog, snmp
    type: string
  type:
    $ref: '../schemas/ip_config_type.yml'
title: Junos_Ip_Config
type: object
