properties:
  auth_key:
    type: string
  bfd_minimum_interval:
    default: 0
    description: 'default:

      * 1000 if `type`==`external``

      * 350  `type`==`internal`'
    maximum: 255000
    minimum: 0
    type: integer
  communities:
    items:
      properties:
        id:
          type: string
        local_preference:
          type: integer
        vpn_name:
          type: string
      title: junos_bgp_community
      type: object
    type: array
  disable_bfd:
    default: false
    description: BFD provides faster path failure detection and is enabled by default
    type: boolean
  export:
    type: string
  export_policy:
    description: default export policies if no per-neighbor policies defined
    type: string
  graceful_restart_time:
    default: 0
    description: '`0` means disable'
    maximum: 4095
    minimum: 0
    type: integer
  hold_time:
    default: 90
    maximum: 65535
    minimum: 0
    type: integer
  import:
    type: string
  import_policy:
    description: default import policies if no per-neighbor policies defined
    type: string
  local_as:
    type: integer
  neighbor_as:
    type: integer
  neighbors:
    additionalProperties:
      properties:
        export_policy:
          type: string
        hold_time:
          default: 90
          maximum: 65535
          minimum: 0
          type: integer
        import_policy:
          type: string
        multihop_ttl:
          description: assuming BGP neighbor is directly connected
          maximum: 255
          minimum: 0
          type: integer
        neighbor_as:
          type: integer
      type: object
    description: if per-neighbor as is desired. Property key is the neighbor address
    title: junos_bgp_neighbor
    type: object
  networks:
    description: if `type`!=`external`or `via`==`wan`networks where we expect BGP
      neighbor to connect to/from
    items:
      type: string
    type: array
  no_readvertise_to_overlay:
    default: false
    description: by default, we'll re-advertise all learned BGP routers toward overlay
    type: boolean
  type:
    enum:
    - internal
    - external
    minLength: 1
    title: junos_bgp_type
    type: string
  via:
    default: lan
    description: network name
    enum:
    - lan
    - wan
    title: junos_bgp_via
    type: string
  vpn_name:
    type: string
  wan_name:
    description: if `via`==`wan`
    type: string
title: Junos_Bgp_Config
type: object
