description: optional, if it's required to have switch's L3 presense on a network/vlan
properties:
  evpn_anycast:
    default: false
    description: for EVPN, if anycast is desired
    type: boolean
  ip:
    description: required if `type`==`static`
    type: string
  netmask:
    description: optional, `subnet` from `network` definition will be used if defined
    type: string
  type:
    $ref: '../schemas/ip_type.yml'
title: Junos_Other_Ip_Configs
type: object
