description: for HA Cluster, node1 can have different IP Config
properties:
  ip:
    type: string
  netmask:
    description: used only if `subnet` is not specified in `networks`
    type: string
  network:
    description: optional, the network to be used for mgmt
    type: string
  type:
    $ref: '../schemas/ip_config_type.yml'
  use_mgmt_vrf:
    default: false
    description: if supported on the platform. If enabled, DNS will be using this
      routing-instance, too
    type: boolean
  use_mgmt_vrf_for_host_out:
    default: false
    description: whether to use `mgmt_junos` for host-out traffic (NTP/TACPLUS/RADIUS/SYSLOG/SNMP),
      if alternative source network/ip is desired
    type: boolean
  vlan_id:
    description: optional, if different from parent
    type: integer
title: Junos_Oob_Ip_Config_Node_1
type: object
