description: Junos IP Config
properties:
  dns:
    $ref: '../schemas/junos-ip-config-gateway-dns.yml'
  dns_suffix:
    $ref: '../schemas/junos-ip-config-gateway-dns-suffix.yml'
  gateway:
    description: except for out-of-band interface (vme/em0/fxp0)
    type: string
  ip:
    type: string
  netmask:
    description: used only if `subnet` is not specified in `networks`
    type: string
  network:
    description: optional, the network to be used for mgmt
    type: string
  poser_password:
    description: if `type`==`pppoe`
    type: string
  ppoe_username:
    description: if `type`==`pppoe`
    type: string
  pppoe_auth:
    $ref: '../schemas/gateway-wan-ppoe-auth.yml'
  type:
    $ref: '../schemas/gateway-wan-type.yml'
title: Junos_Ip_Config_Gateway
type: object
