description: at least one of the `ingress_port_ids`, `egress_port_ids` or `ingress_networks
  ` should be specified
items:
  example: ge-0/0/3
  type: string
title: Junos-Port-Mirroring-Ingress-Port-Ids
type: array
