properties:
  client_list:
    items:
      properties:
        client_list_name:
          example: clist-1
          type: string
        clients:
          items:
            example: 151.140.101.218/32
            type: string
          type: array
      type: object
    type: array
  contact:
    example: cns@juniper.net
    type: string
  description:
    example: Juniper QFX Series Switch - 1K_5LA
    type: string
  enabled:
    default: true
    type: boolean
  engine_id:
    enum:
    - local
    - engine-id-suffix
    - use-default-ip-address
    - use-mac-address
    type: string
  location:
    example: Las Vegas, NV
    type: string
  name:
    example: TGH-1K-QFX10K
    type: string
  network:
    default: default
    type: string
  trap_groups:
    items:
      properties:
        categories:
          items:
            example: authentication
            type: string
          type: array
        group_name:
          description: Categories list can refer to https://www.juniper.net/documentation/software/topics/task/configuration/snmp-trap-groups-configuring-junos-nm.html
          example: profiler
          type: string
        targets:
          items:
            example: 172.29.158.19
            type: string
          type: array
        version:
          default: v2
          enum:
          - v1
          - v2
          - all
          type: string
      type: object
    type: array
  v2c_config:
    items:
      properties:
        authorization:
          example: read-only
          type: string
        client_list_name:
          description: client_list_name here should refer to client_list above
          example: clist-1
          type: string
        community_name:
          example: abc123
          type: string
        view:
          description: view name here should be defined in views above
          example: all
          type: string
      type: object
    type: array
  v3_config:
    properties:
      notify:
        items:
          properties:
            name:
              type: string
            tag:
              type: string
            type:
              enum:
              - trap
              - inform
              type: string
          type: object
        type: array
      notify_filter:
        items:
          properties:
            contents:
              items:
                properties:
                  include:
                    type: boolean
                  oid:
                    example: 1.3.6.1.4.1
                    type: string
                type: object
              type: array
            profile_name:
              type: string
          type: object
        type: array
      target_address:
        items:
          properties:
            address:
              example: address
              type: string
            address_mask:
              example: address_mask
              type: string
            port:
              default: 161
              type: integer
            tag_list:
              description: <refer to notify tag, can be multiple with blank
              type: string
            target_address_name:
              example: target_address_name
              type: string
            target_parameters:
              description: refer to notify target parameters name
              type: string
          type: object
        type: array
      target_parameters:
        items:
          properties:
            message_processing_model:
              enum:
              - v1
              - v2c
              - v3
              type: string
            name:
              type: string
            notify_filter:
              description: refer to profile-name in notify-filter
              type: string
            security_level:
              enum:
              - authentication
              - none
              - privacy
              type: string
            security_model:
              enum:
              - usm
              - v1
              - v2c
              type: string
            security_name:
              description: refer to security_name in usm
              example: m01620
              type: string
          type: object
        type: array
      usm:
        properties:
          engine-id:
            description: required only if `engine_type`==`remote_engine`
            example: 00:00:00:0b:00:00:70:10:6f:08:b6:3f
            type: string
          engine_type:
            enum:
            - remote_engine
            - local_engine
            type: string
          users:
            items:
              properties:
                authentication_password:
                  description: 'Not required if `authentication_type`==`authentication-none`

                    include alphabetic, numeric, and special characters, but it cannot
                    include control characters. '
                  minLength: 7
                  type: string
                authentication_type:
                  description: sha224, sha256, sha384, sha512 are supported in 21.1
                    and newer release
                  enum:
                  - authentication-md5
                  - authentication-sha
                  - authentication-sha224
                  - authentication-sha256
                  - authentication-sha384
                  - authentication-sha512
                  - authentication-none
                  type: string
                encryption_password:
                  description: 'Not required if `encryption_type`==`privacy-none`

                    include alphabetic, numeric, and special characters, but it cannot
                    include control characters'
                  minLength: 8
                  type: string
                encryption_type:
                  enum:
                  - privacy-aes128
                  - privacy-des
                  - privacy-3des
                  - privacy-none
                  type: string
                name:
                  type: string
              type: object
            type: array
        type: object
      vacm:
        properties:
          access:
            items:
              properties:
                group_name:
                  type: string
                prefix_list:
                  items:
                    properties:
                      context_prefix:
                        description: only required if `type`==`context_prefix`
                        example: iil
                        type: string
                      notify_view:
                        description: refer to view name
                        example: all
                        type: string
                      read_view:
                        description: refer to view name
                        example: all
                        type: string
                      security_level:
                        enum:
                        - privacy
                        - authentication
                        - none
                        type: string
                      security_model:
                        enum:
                        - any
                        - usm
                        - v1
                        - v2c
                        type: string
                      type:
                        enum:
                        - default_context_prefix
                        type: string
                      write_view:
                        description: refer to view name
                        example: all
                        type: string
                    type: object
                  type: array
              type: object
            type: array
          security_to_group:
            properties:
              content:
                items:
                  properties:
                    group:
                      description: refer to group_name under access
                      type: string
                    security_name:
                      type: string
                  type: object
                type: array
              security_model:
                enum:
                - usm
                - v1
                - v2c
                type: string
            type: object
        type: object
    type: object
  views:
    properties:
      include:
        description: if the root oid configured is included
        type: boolean
      oid:
        example: 1.3.6.1
        type: string
      view_name:
        example: all
        type: string
    type: object
type: object
