description: Junos OSPF config
properties:
  areas:
    additionalProperties:
      properties:
        no_summary:
          description: for a stub/nssa area, where to avoid forwarding type-3 LSA
            to this area
          type: boolean
      type: object
    description: OSPF areas to run on this device and the corresponding per-area-specific
      configs. Property key is the area
    type: object
  enabled:
    description: whether to rung OSPF on this device
    type: boolean
  reference_bandwidth:
    default: 100M
    description: Bandwidth for calculating metric defaults (9600..4000000000000)
    type: string
title: Junos_Ospf_Config
type: object
