description: '- If HA configuration: key parameter will be nodeX (eg: node1)

  - If there are 2 routing engines, re1 mgmt IP has to be set separately (if desired):
  key parameter = `re1`'
properties:
  ip:
    type: string
  netmask:
    description: used only if `subnet` is not specified in `networks`
    type: string
  network:
    description: optional, the network to be used for mgmt
    type: string
  type:
    $ref: '../schemas/ip_config_type.yml'
title: Junos_Oob_Ip_Config
type: object
