description: Junos IP Config
properties:
  dns:
    description: except for out-of-band interface (vme/em0/fxp0)
    items:
      type: string
    type: array
  dns_suffix:
    description: except for out-of-band interface (vme/em0/fxp0)
    items:
      type: string
    type: array
  gateway:
    description: except for out-of-band interface (vme/em0/fxp0)
    type: string
  ip:
    type: string
  netmask:
    description: used only if `subnet` is not specified in `networks`
    type: string
  network:
    description: optional, the network to be used for mgmt
    type: string
  poser_password:
    description: if `type`==`pppoe`
    type: string
  ppoe_username:
    description: if `type`==`pppoe`
    type: string
  pppoe_auth:
    default: none
    description: if `type`==`pppoe`
    enum:
    - none
    - chap
    - pap
    title: gateway_wan_ppoe_auth
    type: string
  type:
    default: dhcp
    enum:
    - dhcp
    - static
    - ppoe
    title: gateway_wan_type
    type: string
title: Junos_Ip_Config_Gateway
type: object
