description: Junos IP Config
properties:
  dns:
    items:
      type: string
    type: array
  dns_suffix:
    items:
      type: string
    type: array
  gateway:
    type: string
  ip:
    type: string
  netmask:
    description: used only if `subnet` is not specified in `networks`
    type: string
  network:
    description: the network where this mgmt IP reside, this will be used as default
      network for outbound-ssh, dns, ntp, dns, tacplus, radius, syslog, snmp
    type: string
  type:
    $ref: '../schemas/ip_config_type.yml'
  use_mgmt_vrf:
    default: false
    description: for host-out traffic (NTP/TACPLUS/RADIUS/SYSLOG/SNMP)
    type: boolean
title: Junos_Ip_Config
type: object
