additionalProperties:
  properties:
    type:
      enum:
      - string
      - boolean
      - ip
      - hex
      - int16
      - int32
      - uint16
      - uint32
      type: string
    value:
      type: string
  type: object
description: Property key is the DHCP option number
title: Junos_Dhcpd_Config_Options
type: object
