additionalProperties:
  properties:
    disabled:
      default: false
      description: when defined in template, this allows device to override
      type: boolean
    dns_servers:
      description: if `type`==`local` - optional, if not defined, system one will
        be used
      example:
      - 8.8.8.8
      - 4.4.4.4
      items:
        type: string
      type: array
    dns_suffix:
      description: if `type`==`local` - optional, if not defined, system one will
        be used
      example:
      - .mist.local
      - .mist.com
      items:
        type: string
      type: array
    fixed_bindings:
      $ref: '../schemas/junos_dhcpd_config_fixed_bindings.yml'
    gateway:
      description: if `type`==`local` - optional, `ip` will be used if not provided
      example: 192.168.70.1
      type: string
    ip_end:
      description: if `type`==`local`
      example: 192.168.70.200
      type: string
    ip_start:
      description: if `type`==`local`
      example: 192.168.70.100
      type: string
    lease_time:
      default: 86400
      description: in seconds, lease time has to be between 3600 [1hr] - 604800 [1
        week], default is 86400 [1 day]
      maximum: 604800
      minimum: 3600
      type: integer
    options:
      $ref: '../schemas/junos_dhcpd_config_options.yml'
    server_id_override:
      default: false
      description: "`server_id_override`==`true` means the device, when acts as DHCP\
        \ relay and forwards DHCP responses from DHCP server to clients, \nshould\
        \ overwrite the Sever Identifier option (i.e. DHCP option 54) in DHCP responses\
        \ with its own IP address."
      type: boolean
    servers:
      description: if `type`==`relay`
      items:
        type: string
      type: array
    type:
      default: local
      description: DHCP Server (local) or DHCP Relay (relay)
      enum:
      - local
      - relay
      title: junos_dhcp_type
      type: string
    vendor_encapulated:
      $ref: '../schemas/junos_dhcpd_config_vendor_encapulated.yml'
  type: object
description: if DHCP Server/Relay is intended. Property key is the network name
properties:
  enabled:
    type: boolean
title: Junos_Dhcpd_Config
type: object
