description: optional, if it's required to have switch's L3 presense on a network/vlan
properties:
  evpn_anycast:
    default: false
    description: for EVPN, if anycast is desired
    type: boolean
  gateway6:
    example: fdad:b0bc:f29e::1
    type: string
  ip:
    description: required if `type`==`static`
    example: 10.3.3.1
    type: string
  ip6:
    description: required if `type6`==`static`
    example: fdad:b0bc:f29e::3d16
    type: string
  netmask:
    description: optional, `subnet` from `network` definition will be used if defined
    example: 255.255.255.0
    type: string
  netmask6:
    description: optional, `subnet` from `network` definition will be used if defined
    example: /64
    type: string
  type:
    $ref: '../schemas/ip_type.yml'
  type6:
    $ref: '../schemas/ip_type6.yml'
title: Junos_Other_Ip_Configs
type: object
