additionalProperties:
  $ref: '../schemas/junos_oob_ip_config.yml'
description: Junos out-of_band (vme/em0/fxp0) IP config
properties:
  dns:
    $ref: '../schemas/strings.yml'
  dns_suffix:
    $ref: '../schemas/strings.yml'
  gateway:
    type: string
  ip:
    type: string
  netmask:
    description: used only if `subnet` is not specified in `networks`
    type: string
  network:
    description: optional, the network to be used for mgmt
    type: string
  node1:
    $ref: '../schemas/junos_oob_ip_config_node_1.yml'
  type:
    $ref: '../schemas/ip_config_type.yml'
  use_mgmt_vrf:
    default: true
    description: if supported on the platform. If enabled, DNS will be using this
      routing-instance, too
    type: boolean
  use_mgmt_vrf_for_host_out:
    default: false
    description: whether to use `mgmt_junos` for host-out traffic (NTP/TACPLUS/RADIUS/SYSLOG/SNMP),
      if alternative source network/ip is desired
    type: boolean
  vlan_id:
    type: integer
title: Junos_Oob_Ip_Configs
type: object
