additionalProperties:
  properties:
    ip:
      type: string
    name:
      type: string
  type: object
description: Property key is the MAC Address
example:
  5684dae9ac8b:
    ip: 192.168.70.35
    name: John
title: Junos_Dhcpd_Config_Fixed_Bindings
type: object
