properties:
  categories:
    $ref: '../schemas/junos-snmp-config-trap-groups-items-categories.yml'
  group_name:
    description: Categories list can refer to https://www.juniper.net/documentation/software/topics/task/configuration/snmp-trap-groups-configuring-junos-nm.html
    example: profiler
    type: string
  targets:
    $ref: '../schemas/junos-snmp-config-trap-groups-items-targets.yml'
  version:
    $ref: '../schemas/junos-snmp-config-trap-version.yml'
title: Junos-Snmp-Config-Trap-Groups-Items
type: object
