properties:
  client_list:
    $ref: '../schemas/junos-snmp-config-client-list.yml'
  contact:
    example: cns@juniper.net
    type: string
  description:
    example: Juniper QFX Series Switch - 1K_5LA
    type: string
  enabled:
    default: true
    type: boolean
  engine_id:
    $ref: '../schemas/junos-snmp-config-engine-id.yml'
  location:
    example: Las Vegas, NV
    type: string
  name:
    example: TGH-1K-QFX10K
    type: string
  network:
    default: default
    type: string
  trap_groups:
    $ref: '../schemas/junos-snmp-config-trap-groups.yml'
  v2c_config:
    $ref: '../schemas/junos-snmp-config-v2c-config.yml'
  v3_config:
    $ref: '../schemas/snmp-v3-config.yml'
  views:
    $ref: '../schemas/junos-snmp-config-views.yml'
title: Junos_Snmp_Config
type: object
