description: Junos VRRP config
properties:
  enabled:
    type: boolean
  groups:
    properties:
      '{vrrp_group}':
        properties:
          priority:
            type: integer
        type: object
    type: object
title: Junos_Vrrp_Config
type: object
