properties:
  no_summary:
    description: for a stub/nssa area, where to avoid forwarding type-3 LSA to this
      area
    type: boolean
title: Junos-Ospf-Config-Areas-Additional-Properties
type: object
