description: Junos Radius config
properties:
  acct_interim_interval:
    default: 0
    description: how frequently should interim accounting be reported, 60-65535. default
      is 0 (use one specified in Access-Accept request from RADIUS Server). Very frequent
      messages can affect the performance of the radius server, 600 and up is recommended
      when enabled
    maximum: 65535
    minimum: 0
    type: integer
  acct_servers:
    $ref: '../schemas/junos-radius-config-acct-servers.yml'
  auth_servers:
    $ref: '../schemas/junos-radius-config-auth-servers.yml'
  auth_servers_retries:
    default: 3
    description: radius auth session retries
    type: integer
  auth_servers_timeout:
    default: 5
    description: radius auth session timeout
    type: integer
  coa_enabled:
    default: false
    type: boolean
  coa_port:
    default: 3799
    type: integer
  network:
    description: 'use `network`or `source_ip`

      which network the RADIUS server resides, if there''s static IP for this network,
      we''d use it as source-ip'
    type: string
  source_ip:
    description: use `network`or `source_ip`
    type: string
title: Junos_Radius_Config
type: object
