properties:
  client_list_name:
    example: clist-1
    type: string
  clients:
    $ref: '../schemas/junos-snmp-config-client-list-items-clients.yml'
title: Junos-Snmp-Config-Client-List-Items
type: object
