additionalProperties:
  $ref: '../schemas/mxcluster_tunterm_extra_route.yml'
description: extra routes for Mist Tunneled VLANs. Property key is a CIDR
title: Mxcluster_Tunterm_Extra_Routes
type: object
