additionalProperties:
  $ref: '../schemas/mxedge_tunterm_switch_config.yml'
description: if custom vlan settings are desired
properties:
  enabled:
    type: boolean
title: Mxedge_Tunterm_Switch_Configs
type: object
