properties:
  downstream_ports:
    $ref: '../schemas/mxedge-stats-tunterm-port-config-downstream-ports.yml'
  separate_upstream_downstream:
    example: false
    type: boolean
  upstream_ports:
    $ref: '../schemas/mxedge-stats-tunterm-port-config-upstream-ports.yml'
title: Mxedge_Stats_Tunterm_Port_Config
type: object
