properties:
  port_vlan_id:
    type: integer
  vlan_ids:
    $ref: '../schemas/mxedge-tunterm-switch-config-additional-properties-vlan-ids.yml'
title: Mxedge-Tunterm-Switch-Config-Additional-Properties
type: object
