properties:
  enabled:
    default: false
    type: boolean
  querier:
    $ref: '../schemas/tunterm-igmp-snooping-querier.yml'
  vlan_ids:
    $ref: '../schemas/mxedge-tunterm-igmp-snooping-config-vlan-ids.yml'
title: Mxedge-Tunterm-Igmp-Snooping-Config
type: object
