description: ip configuration of the Mist Tunnel interface
properties:
  gateway:
    example: 10.2.1.254
    type: string
  gateway6:
    example: 2001:1010:1010:1010::1
    type: string
  ip:
    description: untagged VLAN
    example: 10.2.1.1
    type: string
  ip6:
    example: 2001:1010:1010:1010::2
    type: string
  netmask:
    example: 255.255.255.0
    type: string
  netmask6:
    example: /64
    type: string
required:
- gateway
- ip
- netmask
title: Mxedge_Tunterm_Ip_Config
type: object
