additionalProperties:
  $ref: '../schemas/mxedge_tunterm_dhcpd_config_property.yml'
description: global and per-VLAN. Property key is the VLAN ID
properties:
  enabled:
    default: false
    type: boolean
  servers:
    $ref: '../schemas/mxedge_tunterm_dhcpd_config_servers.yml'
  type:
    $ref: '../schemas/mxedge_tunterm_dhcpd_type.yml'
title: Mxedge_Tunterm_Dhcpd_Config
type: object
