properties:
  downstream_ports:
    example:
    - '0'
    - '1'
    items:
      type: string
    type: array
  separate_upstream_downstream:
    example: false
    type: boolean
  upstream_ports:
    example:
    - '0'
    - '1'
    items:
      type: string
    type: array
title: Mxedge_Stats_Tunterm_Port_Config
type: object
