description: ip configuration of the Mist Edge out-of-band management interface
properties:
  autoconf6:
    default: true
    type: boolean
  dhcp6:
    default: true
    type: boolean
  dns:
    default:
    - 8.8.8.8
    - 8.8.4.4
    - 2001:4860:4860::8888
    - 2001:4860:4860::8844
    description: 'IPv4 ignored if `type`!=`static`

      IPv6 ignored if `type6`!=`static`'
    example:
    - 8.8.8.8
    - 4.4.4.4
    - 2001:4860:4860::8888
    - 2001:4860:4860::8844
    items:
      type: string
    type: array
  gateway:
    description: if `type`=`static`
    example: 10.2.1.254
    type: string
  gateway6:
    example: 2601:1700:43c0:dc0::1
    type: string
  ip:
    description: if `type`=`static`
    example: 10.2.1.2
    type: string
  ip6:
    example: 2601:1700:43c0:dc0:20c:29ff:fea7:93bc
    type: string
  netmask:
    description: if `type`=`static`
    example: 255.255.255.0
    type: string
  netmask6:
    example: /64
    type: string
  type:
    $ref: '../schemas/ip_type.yml'
  type6:
    $ref: '../schemas/ip_type.yml'
title: Mxedge_Oob_Ip_Config
type: object
