properties:
  enabled:
    default: false
    type: boolean
  servers:
    $ref: '../schemas/mxedge_tunterm_dhcpd_config_servers.yml'
  type:
    $ref: '../schemas/mxedge_tunterm_dhcpd_config_type.yml'
title: Mxedge_Tunterm_Dhcpd_Config_Property
type: object
