properties:
  enabled:
    default: false
    type: boolean
  servers:
    $ref: '../schemas/mxedge-tunterm-dhcpd-config-additional-properties-servers.yml'
  type:
    $ref: '../schemas/mxedge-additional-tunterm-dhcpd-type.yml'
title: Mxedge-Tunterm-Dhcpd-Config-Additional-Properties
type: object
