properties:
  enabled:
    default: false
    type: boolean
  querier:
    $ref: '../schemas/mxedge_tunterm_igmp_snooping_querier.yml'
  vlan_ids:
    $ref: '../schemas/mxedge_tunterm_igmp_snooping_config_vlan_ids.yml'
title: Mxedge_Tunterm_Igmp_Snooping_Config
type: object
