properties:
  gateway:
    example: 192.168.11.1
    type: string
  ip:
    example: 192.168.11.91
    type: string
  netmask:
    example: 255.255.255.0
    type: string
title: Mxedge_Stats_Tunterm_Ip_Config
type: object
