additionalProperties:
  $ref: '../schemas/mxedge-tunterm-dhcpd-config-additional-properties.yml'
description: global and per-VLAN. Property key is the VLAN ID
properties:
  enabled:
    default: false
    type: boolean
  servers:
    $ref: '../schemas/mxedge-tunterm-dhcpd-config-servers.yml'
  type:
    $ref: '../schemas/mxedge-tunterm-dhcpd-type.yml'
title: Mxedge-Tunterm-Dhcpd-Config
type: object
