properties:
  downstream_ports:
    $ref: '../schemas/mxedge_stats_tunterm_port_config_downstream_ports.yml'
  separate_upstream_downstream:
    example: false
    type: boolean
  upstream_ports:
    $ref: '../schemas/mxedge_stats_tunterm_port_config_upstream_ports.yml'
title: Mxedge_Stats_Tunterm_Port_Config
type: object
