additionalProperties:
  $ref: '../schemas/mxedge-tunterm-switch-config-additional-properties.yml'
description: if custom vlan settings are desired
properties:
  enabled:
    type: boolean
title: Mxedge-Tunterm-Switch-Config
type: object
