properties:
  advertised_subnet:
    description: if `routed`==`true`, whether to advertise an aggregated subnet toward
      HUB this is useful when there are multiple networks on SPOKE's side
    example: 172.16.0.0/24
    type: string
  allow_ping:
    description: whether to allow ping from vpn into this routed network
    type: boolean
  destination_nat:
    $ref: '../schemas/network_destination_nat.yml'
  nat_pool:
    description: if `routed`==`false` (usually at Spoke), but some hosts needs to
      be reachable from Hub, a subnet is required to create and advertise the route
      to Hub
    example: 172.16.0.0/26
    type: string
  no_readvertise_to_lan_bgp:
    default: false
    description: toward LAN-side BGP peers
    type: boolean
  no_readvertise_to_lan_ospf:
    default: false
    description: toward LAN-side OSPF peers
    type: boolean
  no_readvertise_to_overlay:
    description: 'toward overlay

      how HUB should deal with routes it received from Spokes'
    type: boolean
  other_vrfs:
    $ref: '../schemas/network-vpn-access-config-other-vrfs.yml'
  routed:
    description: whether this network is routable
    type: boolean
  source_nat:
    $ref: '../schemas/network_source_nat.yml'
  static_nat:
    $ref: '../schemas/network_static_nat.yml'
  summarized_subnet:
    description: 'toward overlay

      how HUB should deal with routes it received from Spokes'
    example: 172.16.0.0/16
    type: string
  summarized_subnet_to_lan_bgp:
    description: toward LAN-side BGP peers
    example: 172.16.0.0/16
    type: string
  summarized_subnet_to_lan_ospf:
    description: toward LAN-side OSPF peers
    example: 172.16.0.0/16
    type: string
title: Network_Vpn_Access_Config
type: object
