description: 'by default, the routes are only readvertised toward the same vrf on
  spoke

  to allow it to be leaked to other vrfs'
items:
  example: iot
  type: string
title: Network_Vpn_Access_Config_Other_Vrfs
type: array
