description: 'by default, the routes are only readvertised toward the same vrf on
  spoke

  to allow it to be leaked to other vrfs'
items:
  example: iot
  type: string
title: Network-Vpn-Access-Config-Other-Vrfs
type: array
