properties:
  disable_local_ssh:
    description: whether to disable local SSH (by default, local SSH is enabled with
      allow_mist in Org is enabled
    type: boolean
  fips_zeroize_password:
    description: password required to zeroize devices (FIPS) on site level
    example: NUKETHESITE
    type: string
  limit_ssh_access:
    default: false
    description: whether to allow certain SSH keys to SSH into the AP (see Site:Setting)
    type: boolean
title: Org_Setting_Security
type: object
