description: Junos OSPF config
properties:
  areas:
    additionalProperties:
      $ref: '../schemas/ospf_config_areas_additional_properties.yml'
    description: OSPF areas to run on this device and the corresponding per-area-specific
      configs. Property key is the area
    type: object
  enabled:
    description: whether to rung OSPF on this device
    type: boolean
  reference_bandwidth:
    default: 100M
    description: Bandwidth for calculating metric defaults (9600..4000000000000)
    type: string
title: Ospf_Config
type: object
