properties:
  channel_24:
    type: integer
  channel_5:
    type: integer
  radio_macs:
    $ref: '../schemas/strings.yml'
  radios:
    $ref: '../schemas/response_config_history_search_item_radios.yml'
  secpolicy_violated:
    type: boolean
  ssids:
    $ref: '../schemas/strings.yml'
  ssids_24:
    $ref: '../schemas/strings.yml'
  ssids_5:
    $ref: '../schemas/strings.yml'
  timestamp:
    type: number
  version:
    type: string
  wlans:
    $ref: '../schemas/response_config_history_search_item_wlans.yml'
required:
- channel_24
- channel_5
- secpolicy_violated
- timestamp
- version
title: Response_Config_History_Search_Item
type: object
