properties:
  channel_24:
    type: integer
  channel_5:
    type: integer
  radio_macs:
    $ref: '../schemas/string_list.yml'
  radios:
    items:
      $ref: '../schemas/response_config_history_search_item_radio.yml'
    type: array
    uniqueItems: true
  secpolicy_violated:
    type: boolean
  ssids:
    $ref: '../schemas/string_list.yml'
  ssids_24:
    $ref: '../schemas/string_list.yml'
  ssids_5:
    $ref: '../schemas/string_list.yml'
  timestamp:
    type: number
  version:
    type: string
  wlans:
    items:
      $ref: '../schemas/response_config_history_search_item_wlan.yml'
    type: array
    uniqueItems: true
required:
- channel_24
- channel_5
- secpolicy_violated
- timestamp
- version
title: config_history
type: object
