properties:
  auth:
    type: string
  bands:
    $ref: '../schemas/string_list.yml'
  id:
    format: uuid
    type: string
  ssid:
    type: string
  vlan_ids:
    $ref: '../schemas/string_list.yml'
required:
- auth
- id
- ssid
title: Response_Config_History_Search_Item_Wlan
type: object
