properties:
  end:
    type: integer
  limit:
    type: integer
  next:
    type: string
  results:
    items:
      $ref: '../schemas/response_config_history_search_item.yml'
    type: array
    uniqueItems: true
  start:
    type: integer
  total:
    type: integer
required:
- end
- limit
- results
- start
- total
title: Response_Config_History_Search
type: object
