properties:
  end:
    type: integer
  limit:
    type: integer
  next:
    type: string
  results:
    $ref: '../schemas/response_config_history_search_results.yml'
  start:
    type: integer
  total:
    type: integer
required:
- end
- limit
- results
- start
- total
title: Response_Config_History_Search
type: object
