description: Applications used for the Gateway configurations
properties:
  addresses:
    $ref: '../schemas/service_addresses.yml'
  app_categories:
    $ref: '../schemas/service_app_categories.yml'
  app_subcategories:
    $ref: '../schemas/service_app_subcategories.yml'
  apps:
    $ref: '../schemas/service_apps.yml'
  created_time:
    readOnly: true
    type: number
  description:
    type: string
  dscp:
    description: for SSR only, when `traffic_type`==`custom`. 0-63 or variable
    type: string
  failover_policy:
    $ref: '../schemas/service_failover_policy.yml'
  hostnames:
    $ref: '../schemas/service_hostnames.yml'
  id:
    format: uuid
    readOnly: true
    type: string
  max_jitter:
    description: for SSR only, when `traffic_type`==`custom`, for uplink selection.
      0-4294967295 or variable
    type: string
  max_latency:
    description: for SSR only, when `traffic_type`==`custom`, for uplink selection.
      0-4294967295 or variable
    type: string
  max_loss:
    description: for SSR only, when `traffic_type`==`custom`, for uplink selection.
      0-100 or variable
    type: string
  modified_time:
    readOnly: true
    type: number
  name:
    type: string
  org_id:
    $ref: '../schemas/org_id.yml'
  sle_enabled:
    default: false
    description: whether to enable measure SLE
    type: boolean
  specs:
    $ref: '../schemas/service_specs.yml'
  ssr_relaxed_tcp_state_enforcement:
    default: false
    type: boolean
  traffic_class:
    $ref: '../schemas/service_traffic_class.yml'
  traffic_type:
    default: data_best_effort
    description: "values from `/api/v1/consts/traffic_types`\n  * when `type`==`apps`,\
      \ we''ll choose traffic_type automatically\n  * when `type`==`addresses` or\
      \ `type`==`hostnames`, you can provide your own settings (optional)"
    type: string
  type:
    $ref: '../schemas/service_type.yml'
  urls:
    $ref: '../schemas/service_urls.yml'
title: Service
type: object
