description: WIP
properties:
  addresses:
    description: if `type`==`custom`, ip subnets
    items:
      type: string
    type: array
  app_caetgories:
    description: 'when `type`==`app_caetgories`

      list of application categories are available through /api/v1/const/app_categories'
    example:
    - Sports
    items:
      type: string
    type: array
  app_subcategories:
    description: 'when `type`==`app_caetgories`

      list of application categories are available through /api/v1/const/app_subcategories'
    example:
    - Shopping
    items:
      type: string
    type: array
  apps:
    description: "when `type`==`apps`\nlist of applications are available through:\n\
      \  - /api/v1/const/applications,\n  - /api/v1/const/gateway_applications\n \
      \ - /insight/top-app-by-bytes?wired=true"
    example:
    - office365
    - okta
    items:
      type: string
    type: array
  created_time:
    readOnly: true
    type: integer
  description:
    type: string
  dscp:
    description: when `traffic_type`==`custom`
    type: integer
  failover_policy:
    $ref: '../schemas/service_failover_policy.yml'
  hostnames:
    description: if `type`==`custom`, web filtering
    items:
      example: example.com
      type: string
    type: array
  id:
    format: uuid
    type: string
  max_jitter:
    description: when `traffic_type`==`custom`, for uplink selection
    type: integer
  max_latency:
    description: when `traffic_type`==`custom`, for uplink selection
    type: string
  max_loss:
    description: when `traffic_type`==`custom`, for uplink selection
    type: integer
  modified_time:
    readOnly: true
    type: integer
  name:
    type: string
  org_id:
    $ref: '../schemas/org_id.yml'
  sle_enabled:
    default: false
    description: whether to enable measure SLE
    type: boolean
  specs:
    $ref: '../schemas/service_spec.yml'
  ssr_relaxed_tcp_state_enforcement:
    default: false
    type: boolean
  traffic_class:
    $ref: '../schemas/service_traffic_class.yml'
  traffic_type:
    default: data_best_effort
    description: 'values from `/api/v1/consts/traffic_types`

      * when `type`==`apps`, we''ll choose traffic_type automatically

      * when `type`==`addresses` or `type`==`hostnames`, you can provide your own
      settings (optional)'
    type: string
  type:
    $ref: '../schemas/service_type.yml'
  urls:
    description: 'when `type`==`urls

      no need for spec as URL can encode the ports being used`'
    items:
      type: string
    type: array
title: Service
type: object
