description: WIP
properties:
  addresses:
    $ref: '../schemas/service_addresses.yml'
  app_caetgories:
    $ref: '../schemas/service_app_caetgories.yml'
  app_subcategories:
    $ref: '../schemas/service_app_subcategories.yml'
  apps:
    $ref: '../schemas/service_apps.yml'
  created_time:
    readOnly: true
    type: integer
  description:
    type: string
  dscp:
    description: when `traffic_type`==`custom`
    type: integer
  failover_policy:
    $ref: '../schemas/service_failover_policy.yml'
  hostnames:
    $ref: '../schemas/service_hostnames.yml'
  id:
    format: uuid
    type: string
  max_jitter:
    description: when `traffic_type`==`custom`, for uplink selection
    type: integer
  max_latency:
    description: when `traffic_type`==`custom`, for uplink selection
    type: integer
  max_loss:
    description: when `traffic_type`==`custom`, for uplink selection
    type: integer
  modified_time:
    readOnly: true
    type: integer
  name:
    type: string
  org_id:
    $ref: '../schemas/org_id.yml'
  sle_enabled:
    default: false
    description: whether to enable measure SLE
    type: boolean
  specs:
    $ref: '../schemas/service_specs.yml'
  ssr_relaxed_tcp_state_enforcement:
    default: false
    type: boolean
  traffic_class:
    $ref: '../schemas/service_traffic_class.yml'
  traffic_type:
    default: data_best_effort
    description: 'values from `/api/v1/consts/traffic_types`

      * when `type`==`apps`, we''ll choose traffic_type automatically

      * when `type`==`addresses` or `type`==`hostnames`, you can provide your own
      settings (optional)'
    type: string
  type:
    $ref: '../schemas/service_type.yml'
  urls:
    $ref: '../schemas/service_urls.yml'
title: Service
type: object
