properties:
  enabled:
    default: false
    type: boolean
  vlan_ids:
    $ref: '../schemas/mxedge_tunterm_multicast_config_ssdp_vlan_ids.yml'
title: Site_Setting_Tunterm_Multicast_Config_Ssdp
type: object
