properties:
  model_specific:
    additionalProperties:
      additionalProperties:
        $ref: '../schemas/ap_port_config.yml'
      description: Property key is the interface(s) (e.g. "eth1,eth2")
      type: object
    description: Property key is the AP model (e.g "AP32")
    example:
      AP32:
        eth1,eth2:
          port_vlan_id: 1
          vlan_ids:
          - 1
          - 10
          - 50
    type: object
title: Site_Setting_Ap_Port_Config
type: object
