description: mist also uses some heuristic rules to prevent destructive configs from
  being pushed
properties:
  no_push:
    default: false
    description: stop any new config from being pushed to the device
    type: boolean
  push_window:
    $ref: '../schemas/site_setting_config_push_policy_push_window.yml'
title: Site_Setting_Config_Push_Policy
type: object
