properties:
  enabled:
    default: false
    type: boolean
  vlan_ids:
    $ref: '../schemas/site-setting-tunterm-multicast-config-mdns-vlan-ids.yml'
title: Site_Setting_Tunterm_Multicast_Config_Mdns
type: object
