description: mist also uses some heuristic rules to prevent destructive configs from
  being pushed
properties:
  no_push:
    $ref: '../schemas/site_config_push_policy_push_window.yml'
    default: false
    description: stop any new config from being pushed to the device
    type: boolean
title: Site_Config_Push_Policy
type: object
