description: 'additional CLI commands to append to the generated config for gateways


  **Note**: no check is done'
items:
  type: string
title: Site-Setting-Gateway-Additional-Config-Cmds
type: array
