description: if enabled, new config will only be pushed to device within the specified
  time window
properties:
  enabled:
    default: true
    type: boolean
  hours:
    $ref: '../schemas/hours.yml'
title: Site_Setting_Config_Push_Policy_Push_Window
type: object
