properties:
  mdns:
    $ref: '../schemas/site_setting_tunterm_multicast_config_mdns.yml'
  multicast_all:
    default: false
    type: boolean
  ssdp:
    $ref: '../schemas/site_setting_tunterm_multicast_config_ssdp.yml'
title: Site_Setting_Tunterm_Multicast_Config
type: object
