description: Site
properties:
  address:
    description: full address of the site
    example: 1601 S. Deanza Blvd., Cupertino, CA, 95014
    type: string
  alarmtemplate_id:
    description: Alarm Template ID, this takes precedence over the Org-level alarmtemplate_id
    example: 684dfc5c-fe77-2290-eb1d-ef3d677fe168
    format: uuid
    nullable: true
    type: string
  aptemplate_id:
    description: AP Template ID, used by APs
    example: 16bdf952-ade2-4491-80b0-85ce506c760b
    type: string
  country_code:
    description: country code for the site (for AP config generation), in two-character
    example: US
    type: string
  created_time:
    readOnly: true
    type: number
  gatewaytemplate_id:
    description: Gateway Template ID, used by gateways
    example: 6f9b2e75-9b2f-b5ae-81e3-e14c76f1a90f
    format: uuid
    nullable: true
    type: string
  id:
    format: uuid
    readOnly: true
    type: string
  latlng:
    $ref: '../schemas/lat_lng.yml'
  modified_time:
    readOnly: true
    type: number
  name:
    example: Mist Office
    type: string
  networktemplate_id:
    description: Network Template ID, this takes precedence over Site Settings
    example: 12ae9bd2-e0ab-107b-72e8-a7a005565ec2
    format: uuid
    nullable: true
    type: string
  notes:
    description: optional, any notes about the site
    type: string
  org_id:
    $ref: '../schemas/org_id.yml'
  rftemplate_id:
    description: RF Template ID, this takes precedence over Site Settings
    example: bb8a9017-1e36-5d6c-6f2b-551abe8a76a2
    format: uuid
    nullable: true
    type: string
  secpolicy_id:
    description: SecPolicy ID
    example: 3bcd0beb-5d0a-4cbd-92c1-14aea91e98ef
    format: uuid
    nullable: true
    type: string
  sitegroup_ids:
    description: sitegroups this site belongs to
    items:
      format: uuid
      type: string
    type: array
  sitetemplate_id:
    description: Site Template ID
    format: uuid
    type: string
  timezone:
    description: Timezone the site is at
    example: America/Los_Angeles
    type: string
required:
- name
title: Site
type: object
