properties:
  enabled:
    default: false
    type: boolean
  vlan_ids:
    example:
    - 2
    - 3
    - 5
    items:
      type: integer
    type: array
title: Site_Setting_Tunterm_Multicast_Config_Ssdp
type: object
