properties:
  app:
    type: string
  degraded:
    type: integer
  duration:
    type: integer
  name:
    type: string
  threshold:
    type: integer
  total:
    type: integer
title: Sle_Impacted_Applications_App
type: object
