properties:
  apps:
    $ref: '../schemas/sle_impacted_applications_apps.yml'
  classifier:
    type: string
  end:
    type: integer
  failure:
    type: string
  limit:
    type: string
  metric:
    type: string
  page:
    type: integer
  start:
    type: integer
  total_count:
    type: integer
title: Sle_Impacted_Applications
type: object
