properties:
  apps:
    items:
      properties:
        app:
          type: string
        degraded:
          type: integer
        duration:
          type: integer
        name:
          type: string
        threshold:
          type: integer
        total:
          type: integer
      type: object
    type: array
  classifier:
    type: string
  end:
    type: integer
  failure:
    type: string
  limit:
    type: string
  metric:
    type: string
  page:
    type: integer
  start:
    type: integer
  total_count:
    type: integer
title: Sle_Impacted_Applications
type: object
