properties:
  notify:
    $ref: '../schemas/snmpv3_config_notify.yml'
  notify_filter:
    $ref: '../schemas/snmpv3_config_notify_filter.yml'
  target_address:
    $ref: '../schemas/snmpv3_config_target_address.yml'
  target_parameters:
    $ref: '../schemas/snmpv3_config_target_params.yml'
  usm:
    $ref: '../schemas/snmp_usm.yml'
  vacm:
    $ref: '../schemas/snmp_vacm.yml'
title: Snmpv3_Config
type: object
