properties:
  include:
    description: if the root oid configured is included
    type: boolean
  oid:
    example: 1.3.6.1
    type: string
  view_name:
    example: all
    type: string
title: Snmp_Config_Views
type: object
