properties:
  client_list:
    $ref: '../schemas/snmp_config_client_lists.yml'
  contact:
    example: cns@juniper.net
    type: string
  description:
    example: Juniper QFX Series Switch - 1K_5LA
    type: string
  enabled:
    default: true
    type: boolean
  engine_id:
    $ref: '../schemas/snmp_config_engine_id.yml'
  location:
    example: Las Vegas, NV
    type: string
  name:
    example: TGH-1K-QFX10K
    type: string
  network:
    default: default
    type: string
  trap_groups:
    $ref: '../schemas/snmp_config_trap_groups.yml'
  v2c_config:
    $ref: '../schemas/snmp_config_v2c_configs.yml'
  v3_config:
    $ref: '../schemas/snmpv3_config.yml'
  views:
    $ref: '../schemas/snmp_config_views.yml'
title: Snmp_Config
type: object
