properties:
  authorization:
    example: read-only
    type: string
  client_list_name:
    description: client_list_name here should refer to client_list above
    example: clist-1
    type: string
  community_name:
    example: abc123
    type: string
  view:
    description: view name here should be defined in views above
    example: all
    type: string
title: snmp_v2c_config
type: object
