properties:
  categories:
    $ref: '../schemas/snmp_config_trap_group_categories.yml'
  group_name:
    description: Categories list can refer to https://www.juniper.net/documentation/software/topics/task/configuration/snmp_trap-groups-configuring-junos-nm.html
    example: profiler
    type: string
  targets:
    $ref: '../schemas/snmp_config_trap_group_targets.yml'
  version:
    $ref: '../schemas/snmp_config_trap_verion.yml'
title: Snmp_Config_Trap_Group
type: object
