properties:
  message_processing_model:
    $ref: '../schemas/snmpv3_config_target_param_mess_process_model.yml'
  name:
    type: string
  notify_filter:
    description: refer to profile-name in notify_filter
    type: string
  security_level:
    $ref: '../schemas/snmpv3_config_target_param_security_level.yml'
  security_model:
    $ref: '../schemas/snmpv3_config_target_param_security_model.yml'
  security_name:
    description: refer to security_name in usm
    example: m01620
    type: string
title: Snmpv3_Config_Target_Param
type: object
