properties:
  address:
    example: address
    type: string
  address_mask:
    example: address_mask
    type: string
  port:
    default: 161
    type: integer
  tag_list:
    description: <refer to notify tag, can be multiple with blank
    type: string
  target_address_name:
    example: target_address_name
    type: string
  target_parameters:
    description: refer to notify target parameters name
    type: string
title: Snmpv3_Config_Target_Address_Item
type: object
