properties:
  notify:
    $ref: '../schemas/snmp-v3-config-notify.yml'
  notify_filter:
    $ref: '../schemas/snmp-v3-config-notify-filter.yml'
  target_address:
    $ref: '../schemas/snmp-v3-config-target-address.yml'
  target_parameters:
    $ref: '../schemas/snmp-v3-config-target-parameters.yml'
  usm:
    $ref: '../schemas/snmp-usm.yml'
  vacm:
    $ref: '../schemas/snmp-vacm.yml'
title: snmp_v3_config
type: object
