description: 'enum: `engine-id-suffix`, `local`, `use-default-ip-address`, `use_mac-address`'
enum:
- engine-id-suffix
- local
- use-default-ip-address
- use_mac-address
title: Snmp_Config_Engine_Id
type: string
