properties:
  message_processing_model:
    $ref: '../schemas/snmp-v3-config-target-parameters-items-message-processing-model.yml'
  name:
    type: string
  notify_filter:
    description: refer to profile-name in notify-filter
    type: string
  security_level:
    $ref: '../schemas/snmp-v3-config-target-parameters-items-security-level.yml'
  security_model:
    $ref: '../schemas/snmp-v3-config-target-parameters-items-security-model.yml'
  security_name:
    description: refer to security_name in usm
    example: m01620
    type: string
title: Snmp-V3-Config-Target-Parameters-Items
type: object
