description: '- If HA configuration: key parameter will be nodeX (eg: node1)

  - If there are 2 routing engines, re1 mgmt IP has to be set separately (if desired):
  key parameter = `re1`'
properties:
  gateway:
    type: string
  ip:
    type: string
  netmask:
    description: used only if `subnet` is not specified in `networks`
    type: string
  network:
    description: optional, the network to be used for mgmt
    type: string
  type:
    $ref: '../schemas/ip_type.yml'
  use_mgmt_vrf:
    default: false
    description: f supported on the platform. If enabled, DNS will be using this routing-instance,
      too
    type: boolean
  use_mgmt_vrf_for_host_out:
    default: false
    description: for host-out traffic (NTP/TACPLUS/RADIUS/SYSLOG/SNMP), if alternative
      source network/ip is desired,
    type: boolean
title: Switch_Oob_Ip_Config
type: object
