additionalProperties:
  properties:
    discard:
      default: false
      description: this takes precedence
      type: boolean
    metric:
      example: null
      maximum: 4294967295
      minimum: 0
      nullable: true
      type: integer
    next_qualified:
      additionalProperties:
        properties:
          metric:
            nullable: true
            type: integer
          preference:
            nullable: true
            type: integer
        type: object
      example:
        10.3.1.1:
          metric: null
          preference: 40
      type: object
    no_resolve:
      default: false
      type: boolean
    preference:
      example: 30
      maximum: 4294967295
      minimum: 0
      nullable: true
      type: integer
    via:
      description: next-hop IP Address
      example: 10.2.1.1
      type: string
  type: object
title: Switch_Extra_Routes
