additionalProperties:
  $ref: '../schemas/junos_port_config.yml'
description: Propery key is the interface name or interface range
example:
  '*':
    usage: default
  ge-0/0/0-1:
    ae_disable_lacp: false
    ae_idx: 0
    aggregated: true
    critical: true
    usage: uplink
  ge-0/0/8-16,ge-1/0/0-47:
    usage: ap
title: Switch_Matching_Rule_Port_Config
type: object
