additionalProperties:
  properties:
    discard:
      default: false
      description: this takes precedence
      type: boolean
    metric:
      example: null
      nullable: true
      type: integer
    next_qualified:
      additionalProperties:
        properties:
          metric:
            nullable: true
            type: integer
          preference:
            nullable: true
            type: integer
        type: object
      example:
        10.3.1.1:
          metric: null
          preference: 40
      type: object
    no_resolve:
      default: false
      type: boolean
    preference:
      example: 30
      nullable: true
      type: integer
    via:
      description: next-hop IP Address
      type: string
  type: object
description: Property key is the destination CIDR (e.g. "10.0.0.0/8")
example:
  172.16.3.0/24:
    via: 10.2.1.1
  it_mgmt:
    discard: false
    metric: null
    next_qualified:
      10.3.1.1:
        metric: null
        preference: 40
    no_resolve: false
    preference: 30
    via: 10.2.1.1
  type: object
title: Switch_Extra_Routes
