properties:
  disabled:
    default: false
    type: boolean
  vlans:
    $ref: '../schemas/synthetictest_config_vlans.yml'
  wan_speedtest:
    $ref: '../schemas/synthetictest_config_wan_speedtest.yml'
title: Synthetictest_Config
type: object
