properties:
  archive:
    $ref: '../schemas/syslog_file_config_archive.yml'
  contents:
    $ref: '../schemas/syslog_file_config_contents.yml'
  explicit_priority:
    type: boolean
  file:
    example: file-name
    type: string
  match:
    example: '!alarm|ntp|errors.crc_error[chan]'
    type: string
  structured_data:
    type: boolean
title: Syslog_File_Config
type: object
