properties:
  archive:
    $ref: '../schemas/syslog-file-config-archive.yml'
  contents:
    $ref: '../schemas/syslog-file-config-contents.yml'
  explicit_priority:
    type: boolean
  file:
    example: file-name
    title: snmp_file
    type: string
  match:
    example: '!alarm|ntp|errors.crc_error[chan]'
    type: string
  structured_data:
    type: boolean
title: syslog_file_config
type: object
