properties:
  auto_provision:
    $ref: '../schemas/tunnel_configs_auto_provision.yml'
  ike_lifetime:
    description: Only if `provider`== `custom-ipsec`
    type: integer
  ike_mode:
    $ref: '../schemas/gateway_template_tunnel_ike_mode.yml'
  ike_proposals:
    $ref: '../schemas/tunnel_configs_ike_proposals.yml'
  ipsec_lifetime:
    description: if `provider`== `custom-ipsec`
    type: integer
  ipsec_proposals:
    $ref: '../schemas/tunnel_configs_ipsec_proposals.yml'
  local_id:
    description: "Only if:\n  * `provider`== `zscaler-ipsec`\n  * `provider`==`jse-ipsec`\n\
      \  * `provider`== `custom-ipsec`"
    type: string
  mode:
    $ref: '../schemas/gateway_template_tunnel_mode.yml'
  primary:
    $ref: '../schemas/gateway_template_tunnel_node.yml'
  probe:
    $ref: '../schemas/gateway_template_tunnel_probe.yml'
  protocol:
    $ref: '../schemas/gateway_template_tunnel_protocol.yml'
  provider:
    $ref: '../schemas/tunnel_provider_options_name.yml'
  psk:
    description: "Only if:\n  * `provider`== `zscaler-ipsec`\n  * `provider`==`jse-ipsec`\n\
      \  * `provider`== `custom-ipsec`"
    type: string
  secondary:
    $ref: '../schemas/gateway_template_tunnel_node.yml'
  version:
    $ref: '../schemas/gateway_template_tunnel_version.yml'
title: Tunnel_Configs
type: object
