properties:
  enable:
    type: boolean
  latlng:
    $ref: '../schemas/lat_lng.yml'
  primary:
    $ref: '../schemas/tunnel_configs_auto_provision_node.yml'
  region:
    $ref: '../schemas/tunnel_configs_auto_provision_region.yml'
  secondary:
    $ref: '../schemas/tunnel_configs_auto_provision_node.yml'
title: Tunnel_Configs_Auto_Provision
type: object
