default: '14'
description: "Only if `provider`== `custom-ipsec`. Possible values:\n  * 1 \n  * 2\
  \ (1024-bit)\n  * 5\n  * 14 (default, 2048-bit)\n  * 15 (3072-bit)\n  * 16 (4096-bit)\n\
  \  * 19 (256-bit ECP)\n  * 20 (384-bit ECP)\n  * 21 (521-bit ECP)\n  * 24 (2048-bit\
  \ ECP)"
enum:
- '1'
- '2'
- '5'
- '14'
- '15'
- '16'
- '19'
- '20'
- '21'
- '24'
title: Tunnel_Configs_Dh_Group
type: string
