default: aes256
description: 'enum: `3des`, `aes128`, `aes256`, `aes_gcm128`, `aes_gcm256`'
enum:
- 3des
- aes128
- aes256
- aes_gcm128
- aes_gcm256
nullable: true
title: Tunnel_Configs_Enc_Algo
type: string
