additionalProperties:
  properties:
    enabled:
      default: false
      type: boolean
    servers:
      $ref: '../schemas/string_list.yml'
    type:
      $ref: '../schemas/tunterm_dhcpd_type.yml'
  type: object
description: DHCP server/relay configuration of Mist Tunneled VLANs. Property key
  is the VLAN ID
properties:
  enabled:
    default: false
    type: boolean
  servers:
    $ref: '../schemas/string_list.yml'
  type:
    $ref: '../schemas/tunterm_dhcpd_type.yml'
title: Tunterm_Dhcpd_Config
type: object
