properties:
  enabled:
    default: false
    type: boolean
  servers:
    $ref: '../schemas/strings.yml'
  type:
    $ref: '../schemas/tunterm_dhcpd_type.yml'
title: Tunterm-Dhcpd-Config-Additional-Properties
type: object
