description: ethernet port configurations
properties:
  downstream_ports:
    $ref: '../schemas/tunterm_port_config_downstream_ports.yml'
  separate_upstream_downstream:
    default: false
    description: weather to separate upstream / downstream ports. default is false
      where all ports will be used.
    type: boolean
  upstream_port_vlan_id:
    default: 1
    description: native VLAN id for upstream ports
    example: 30
    type: integer
  upstream_ports:
    $ref: '../schemas/tunterm_port_config_upstream_ports.yml'
title: Tunterm_Port_Config
type: object
