description: ethernet port configurations
properties:
  downstream_ports:
    description: list of ports to be used for downstream (to AP) purpose
    example:
    - '2'
    - '3'
    items:
      type: string
    type: array
  separate_upstream_downstream:
    default: false
    description: weather to separate upstream / downstream ports. default is false
      where all ports will be used.
    type: boolean
  upstream_port_vlan_id:
    default: 1
    description: native VLAN id for upstream ports
    example: 30
    type: integer
  upstream_ports:
    description: list of ports to be used for upstrea purpose (to LAN)
    example:
    - '0'
    - '1'
    items:
      type: string
    type: array
title: Tunterm_Port_Config
type: object
