additionalProperties:
  $ref: '../schemas/tunterm-dhcpd-config-additional-properties.yml'
description: DHCP server/relay configuration of Mist Tunneled VLANs. Property key
  is the VLAN ID
properties:
  enabled:
    default: false
    type: boolean
  servers:
    $ref: '../schemas/strings.yml'
  type:
    $ref: '../schemas/tunterm_dhcpd_type.yml'
title: Tunterm_Dhcpd_Config
type: object
