properties:
  end:
    example: 1508823743
    type: number
  endDate:
    example: 10/23/2017
    type: string
  interval:
    example: 1d
    type: string
  name:
    example: Past 7 Days
    type: string
  shortName:
    example: 7d
    type: string
  start:
    example: 1508223600
    type: integer
  usePreset:
    example: true
    type: boolean
title: Ui-Settings-Tiles-Items-Time-Range
type: object
