properties:
  chartBand:
    example: 2.4 ghz
    type: string
  chartColor:
    example: '#00B4AD'
    type: string
  chartDirection:
    example: tx + rx
    type: string
  chartRankBy:
    type: string
  chartType:
    example: timeSeries
    type: string
  colspan:
    example: 5
    type: integer
  column:
    example: 1
    type: integer
  hideEmptyRows:
    type: boolean
  id:
    example: 7a9ab38c-cfc3-483d-b51a-0aec571fadc0
    format: uuid
    type: string
  metric:
    $ref: '../schemas/ui-settings-tiles-items-metric.yml'
  name:
    example: New Analysis
    type: string
  row:
    example: 1
    type: integer
  rowspan:
    example: 2
    type: integer
  scopeId:
    example: e0c767834b4c
    type: string
  scopeType:
    example: client
    type: string
  sortedColumns: {}
  timeRange:
    $ref: '../schemas/ui-settings-tiles-items-time-range.yml'
  trendType:
    example: line
    type: string
  vizType:
    example: averageTimeSeriesChart
    type: string
title: Ui-Settings-Tiles-Items
type: object
