properties:
  end:
    example: 1508828400
    type: integer
  endDate:
    example: 10/23/2017
    type: string
  interval:
    example: 1d
    type: string
  name:
    example: This Week
    type: string
  shortName:
    example: thisWeek
    type: string
  start:
    example: 1508655600
    type: integer
  usePreset:
    example: true
    type: boolean
title: Ui-Settings-Default-Time-Range
type: object
