description: UI Settings
properties:
  created_time:
    example: 1508823803
    readOnly: true
    type: number
  defaultScopeId:
    example: 67970e46-4e12-11e6-9188-0242ad112847
    type: string
  defaultScopeType:
    example: site
    type: string
  defaultTimeRange:
    $ref: '../schemas/ui_settings_default_time_range.yml'
  description:
    example: Description of the databoard
    type: string
  for_site:
    example: true
    readOnly: true
    type: boolean
  id:
    example: 3bdcc7e8-c04d-4512-b4fc-093da9057eb0
    format: uuid
    readOnly: true
    type: string
  isCustomDataboard:
    type: boolean
  isScopeLinked:
    type: boolean
  isTimeRangeLinked:
    type: boolean
  modified_time:
    example: 1508823803
    readOnly: true
    type: number
  name:
    example: New Databoard
    type: string
  org_id:
    $ref: '../schemas/org_id.yml'
  purpose:
    example: databoard
    type: string
  site_id:
    $ref: '../schemas/site_id.yml'
  tiles:
    $ref: '../schemas/ui_settings_tiles.yml'
required:
- created_time
- description
- for_site
- id
- modified_time
- org_id
- purpose
- site_id
title: Ui_Settings
type: object
