description: UI Settings
properties:
  created_time:
    example: 1508823803
    readOnly: true
    type: number
  defaultScopeId:
    example: 67970e46-4e12-11e6-9188-0242ad112847
    type: string
  defaultScopeType:
    example: site
    type: string
  defaultTimeRange:
    properties:
      end:
        example: 1508828400
        type: integer
      endDate:
        example: 10/23/2017
        type: string
      interval:
        example: 1d
        type: string
      name:
        example: This Week
        type: string
      shortName:
        example: thisWeek
        type: string
      start:
        example: 1508655600
        type: integer
      usePreset:
        example: true
        type: boolean
    type: object
  description:
    example: Description of the databoard
    type: string
  for_site:
    example: true
    readOnly: true
    type: boolean
  id:
    example: 3bdcc7e8-c04d-4512-b4fc-093da9057eb0
    format: uuid
    readOnly: true
    type: string
  isCustomDataboard:
    type: boolean
  isScopeLinked:
    type: boolean
  isTimeRangeLinked:
    type: boolean
  modified_time:
    example: 1508823803
    readOnly: true
    type: number
  name:
    example: New Databoard
    type: string
  org_id:
    example: cc079380-5029-4d4a-9125-858de85731ff
    format: uuid
    readOnly: true
    type: string
  purpose:
    example: databoard
    type: string
  site_id:
    example: 67970e46-4e12-11e6-9188-0242ad112847
    format: uuid
    readOnly: true
    type: string
  tiles:
    items:
      properties:
        chartBand:
          example: 2.4 ghz
          type: string
        chartColor:
          example: '#00B4AD'
          type: string
        chartDirection:
          example: tx + rx
          type: string
        chartRankBy:
          type: string
        chartType:
          example: timeSeries
          type: string
        colspan:
          example: 5
          type: integer
        column:
          example: 1
          type: integer
        hideEmptyRows:
          type: boolean
        id:
          example: 7a9ab38c-cfc3-483d-b51a-0aec571fadc0
          format: uuid
          type: string
        metric:
          properties:
            apiName:
              example: client-dhcp-latency
              type: string
          type: object
        name:
          example: New Analysis
          type: string
        row:
          example: 1
          type: integer
        rowspan:
          example: 2
          type: integer
        scopeId:
          example: e0c767834b4c
          type: string
        scopeType:
          example: client
          type: string
        sortedColumns: {}
        timeRange:
          properties:
            end:
              example: 1508823743
              type: number
            endDate:
              example: 10/23/2017
              type: string
            interval:
              example: 1d
              type: string
            name:
              example: Past 7 Days
              type: string
            shortName:
              example: 7d
              type: string
            start:
              example: 1508223600
              type: integer
            usePreset:
              example: true
              type: boolean
          type: object
        trendType:
          example: line
          type: string
        vizType:
          example: averageTimeSeriesChart
          type: string
      type: object
    minItems: 1
    type: array
    uniqueItems: true
required:
- created_time
- description
- for_site
- id
- modified_time
- org_id
- purpose
- site_id
title: Ui_Settings
type: object
