properties:
  bands:
    description: list of bands
    items:
      type: string
    type: array
  force:
    default: false
    description: whether to reset those with radio disabled. default is false (i.e.
      if user intentionally disables a radio, honor it)
    type: boolean
required:
- bands
title: Utils_Reset_Radio_Config
type: object
