description: Virtual Chassis
properties:
  members:
    items:
      properties:
        mac:
          description: fpc0, same as the mac of device_id
          type: string
        member:
          description: to create a preprovisionned virtual chassis
          type: integer
        vc_ports:
          items:
            type: string
          type: array
        vc_role:
          enum:
          - master
          - backup
          - linecard
          type: string
      required:
      - mac
      - vc_ports
      - vc_role
      title: virtual_chassis_member
      type: object
    type: array
  preprovisioned:
    default: false
    description: To create the Virtual Chassis in Pre-Provisioned mode
    type: boolean
title: Virtual_Chassis_Config
type: object
