description: Virtual Chassis
properties:
  locating:
    readOnly: true
    type: boolean
  members:
    items:
      $ref: '../schemas/virtual_chassis_config_member.yml'
    type: array
  preprovisioned:
    default: false
    description: To create the Virtual Chassis in Pre-Provisioned mode
    type: boolean
title: Virtual_Chassis_Config
type: object
