properties:
  locating:
    readOnly: true
    type: boolean
  mac:
    description: fpc0, same as the mac of device_id
    type: string
  member:
    description: to create a preprovisionned virtual chassis
    type: integer
  vc_ports:
    $ref: '../schemas/strings.yml'
  vc_role:
    $ref: '../schemas/virtual_chassis_config_member_vc_role.yml'
title: Virtual_Chassis_Config_Member
type: object
