properties:
  locating:
    readOnly: true
    type: boolean
  mac:
    description: fpc0, same as the mac of device_id
    type: string
  member:
    description: to create a preprovisionned virtual chassis
    type: integer
  vc_ports:
    $ref: '../schemas/string_list.yml'
  vc_role:
    enum:
    - master
    - backup
    - linecard
    type: string
title: Virtual_Chassis_Config_Member
type: object
