additionalProperties:
  $ref: '../schemas/vrf_extra_route.yml'
description: Property key is the destination CIDR (e.g. "10.0.0.0/8")
example:
  0.0.0.0/0:
    via: 192.168.1.10
title: Vrf_Extra_Routes
type: object
