title: ''
type: object
properties:
  name:
    type: string
    minLength: 1
  app_key:
    type: string
    minLength: 1
  monitored:
    type: boolean
  specs:
    type: object
    properties:
      protocol:
        type: string
        default: any
        enum:
          - tcp
          - udp
          - icmp
          - gre
          - any
          - ':protocol_number'
        description: 'tcp / udp / icmp / gre / any / ":protocol_number", `protocol_number` is between 1-254, default is `any`'
      subnets:
        type: array
        description: 'matched dst subnet, default is "0.0.0.0/0"'
        items:
          type: string
      hostname:
        type: array
        description: ' matched hostnames'
        items:
          type: string
      port_range:
        type: integer
        minimum: 0
        description: 'matched dst port, "0" means any, default is "0"'
required:
  - name
  - app_key
  - monitored
x-examples:
  predefined:
    name: zoom
    app_key: zoom
    monitored: true
  custom:
    name: zoom
    monitored: true
    app_key: custom
    specs:
      - protocol: tcp
        subnets:
          - 10.1.2.0/24
        hostnames:
          - www.abc.com
        port_range: '80'
description: application
