description: ''
type: object
x-examples:
  example-1:
    isScopeLinked: true
    defaultScopeId: 67970e46-4e12-11e6-9188-0242ad112847
    name: New Databoard
    defaultScopeType: site
    isCustomDataboard: true
    isTimeRangeLinked: true
    tiles:
      - sortedColumns: null
        rowspan: 2
        chartBand: 2.4 ghz
        name: New Analysis
        column: 1
        colspan: 5
        metric:
          apiName: client-dhcp-latency
        timeRange:
          end: 1508823743
          name: Past 7 Days
          interval: 1d
          start: 1508223600
          usePreset: true
          endDate: 10/23/2017
          shortName: 7d
        chartDirection: tx + rx
        chartRankBy: ''
        scopeType: client
        hideEmptyRows: true
        scopeId: e0c767834b4c
        chartType: timeSeries
        vizType: averageTimeSeriesChart
        row: 1
        trendType: line
        id: 7a9ab38c-cfc3-483d-b51a-0aec571fadc0-j956nurl
        chartColor: '#00B4AD'
    defaultTimeRange:
      end: 1508828400
      name: This Week
      interval: 1d
      start: 1508655600
      usePreset: true
      endDate: 10/23/2017
      shortName: thisWeek
    description: Description of the databoard
    id: 3bdcc7e8-c04d-4512-b4fc-093da9057eb0
    for_site: true
    site_id: 67970e46-4e12-11e6-9188-0242ad112847
    org_id: 6748cfa6-4e12-11e6-9188-0242asfad8365
    created_time: 1508823803
    modified_time: 1508823803
    purpose: databoard
properties:
  isScopeLinked:
    type: boolean
  defaultScopeId:
    type: string
    minLength: 1
  name:
    type: string
    minLength: 1
  defaultScopeType:
    type: string
    minLength: 1
  isCustomDataboard:
    type: boolean
  isTimeRangeLinked:
    type: boolean
  tiles:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      type: object
      properties:
        sortedColumns: {}
        rowspan:
          type: number
        chartBand:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        column:
          type: number
        colspan:
          type: number
        metric:
          type: object
          properties:
            apiName:
              type: string
              minLength: 1
        timeRange:
          type: object
          properties:
            end:
              type: number
            name:
              type: string
              minLength: 1
            interval:
              type: string
              minLength: 1
            start:
              type: number
            usePreset:
              type: boolean
            endDate:
              type: string
              minLength: 1
            shortName:
              type: string
              minLength: 1
        chartDirection:
          type: string
          minLength: 1
        chartRankBy:
          type: string
        scopeType:
          type: string
          minLength: 1
        hideEmptyRows:
          type: boolean
        scopeId:
          type: string
          minLength: 1
        chartType:
          type: string
          minLength: 1
        vizType:
          type: string
          minLength: 1
        row:
          type: number
        trendType:
          type: string
          minLength: 1
        id:
          type: string
          minLength: 1
        chartColor:
          type: string
          minLength: 1
  defaultTimeRange:
    type: object
    properties:
      end:
        type: number
      name:
        type: string
        minLength: 1
      interval:
        type: string
        minLength: 1
      start:
        type: number
      usePreset:
        type: boolean
      endDate:
        type: string
        minLength: 1
      shortName:
        type: string
        minLength: 1
  description:
    type: string
    minLength: 1
  id:
    type: string
    minLength: 1
  for_site:
    type: boolean
  site_id:
    type: string
    minLength: 1
  org_id:
    type: string
    minLength: 1
  created_time:
    type: number
  modified_time:
    type: number
  purpose:
    type: string
    minLength: 1
required:
  - description
  - id
  - for_site
  - site_id
  - org_id
  - created_time
  - modified_time
  - purpose
